### PR TITLE
fix(rest): Fix status code when moderation request is created as a part of an API call

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Fix status code when moderation request is created as a part of an API call
>  * Affected APIs in ProjectController - Update Project, Add/Patch Releases to a project, Patch vulnerabilities of a project, Add Attachment To Project
>  * Affected APIs in ReleaseController - Update Releases, Delete Attachments from releases
>  * Affected APIs in ComponentController - Delete Attachments from component, Delete Components, Update Components, Add Attachment To Component

> * Which issue is this pull request belonging to and how is it solving it? (*#1003*)
> * Did you add or update any new dependencies that are required for your change? - No

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by ravi110336** [comment]
For update components API, the response status is perfectly fine with status code 202, but the response element is showing the updated element value but when we go and validate it in sw360 it didn't updated for user token which is correct instead it should create moderation request.

I think in these scenarios for status 202, we should have one generic response message like "Moderation Request is created."

image

**Comment by JaideepPalit** [comment]
Thanks for review and test. 
Added proper message in response body when moderation request is created.

**Comment by ravi110336** [comment]
Thanks Jaideep. Tested and working fine now, we can merge this.

image
image

**Review by ravi110336 — APPROVED** [review]
Code looks good, kindly merge.

**Pull request merged**
