### PR TITLE
Fix(Project GUI): Fix bug missing obligation text when change status or comment of component, project, organisation obligation in project edit

### PR DESCRIPTION
**Pull request by hoangnt2**
Issue: #1778 

### How To Test?
Refer to: #1778 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by nikkuma7** [comment]
image
I create a two- component obligation with different status, but the text is still showing.

**Comment by hoangnt2** [comment]
Hi @nikkuma7,
Currently, when change status of obligation, the text will be disappear. So your result is correct.

**Comment by nikkuma7** [comment]
Hi @hoangnt2 
Thank you.

Test successful.

**Review by ag4ums — APPROVED** [review]
Code looks good

**Pull request merged**
