### PR TITLE
Updating files for release 7.0.1-M1

### PR DESCRIPTION
**Pull request by mcjaeger**
Release fixes two bugs in 7.0.0-M1

* a lost character in some file has damaged a view
* depending on context a pop-up dialogue to enter values to not render

This PR changes files accordingly for 7.0.1-M1 in order to tag

### CODE REVIEW

**Comment by mcjaeger** [comment]
note:

test for auth server did not run on my local machine:

```
:: sw360 Authorization Server :: Running Spring Boot 1.5.8.RELEASE ::

2020-01-30 11:10:13 INFO  OAuthClientControllerTest:48 - Starting OAuthClientControllerTest on lando-2.local with PID 1594 (started by sam in /Users/Shared/sw360rel701/sw360/rest/authorization-server)
 2020-01-30 11:10:13 INFO  OAuthClientControllerTest:597 - The following profiles are active: dev,test
 2020-01-30 11:10:13 ERROR SpringApplication:771 - Application startup failed
 java.lang.IllegalStateException: Cannot load configuration class: org.eclipse.sw360.rest.authserver.Sw360AuthorizationServer
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:403)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:249)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:127)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
```
but I suspect it is because of my local couchdb config

**Comment by mcjaeger** [comment]
tests seem to run in CI though

**Comment by mcjaeger** [comment]
tested with Vagrant deployment on existing data:

* open all main views
* open all admin views
* create component, release, project
* edit component, release project
* edits with external id, additional data, addtional roles
* create project with second hierarchy level
* generate license info only own
* generate license info with hierarchy
* cerate spreadsheets
* search
* create vendor
* create license
* create todo (and look if it appears in the projects)
* edit project obligations
* bulk release edit
* schedule services
* create link from release to project
* add moderator
* check links between different views (etc -> release, release -> project, project -> release)
* version string OK

**Comment by maxhbr** [comment]
Deployment with Docker also works

**Pull request merged**
