### PR TITLE
chore(ui): Display banner warning for IE

### PR DESCRIPTION
**Pull request by maierthomas**
- display banner warning for Internet Explorer usage

Signed-off-by: Thomas Maier <thomas.maier@evosoft.com>

### CODE REVIEW

**Comment by maierthomas** [comment]
from discussion: move onload function and IE browser detect to theme and separate to a new js file.

**Comment by maierthomas** [comment]
updated, moved to sw360-theme

**Comment by kallesoranko** [comment]
Tested and working correctly. Warning banner is shown in IE and Edge.
image

**Comment by kallesoranko** [comment]
Code looks fine 👍

**Pull request merged**
