### PR TITLE
fix(merge): allow merging of complex fields, style improvements

### LINKED ISSUE #596: Component merge does not seem to be able to handle complex fields
the backend code of the component merge looks like that it is not build to handle complex fields like `externalIds` or `additionalRoles`.
https://github.com/eclipse/sw360/blob/b8dffa51f6b8a4305fc7ebb16b45214b472d6ebe/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java#L501-L509

 It just merges "plainFields", Releases and Attachments.

### PR DESCRIPTION
**Pull request by lepokle**
* Merging complex fields
This commits fixes the merge of the two complex fields 'external ids' and
'additional data' in components.

* Style impprovements
Layout and style of merge wizard have been improved. Style for DisplayMap
(for external ids and additonal data) has been improved.

Closes #596

Signed-off-by: Leo von Klenze <leo.vonklenze@scansation.de>

### CODE REVIEW

**Comment by nutanv1contr** [comment]
Tested the PR. I am assuming there are two issues with merging 'external ids' and 'additional data'. 

Issue 1: 
1. Create two components with external id and additional data added.
2. Try to merge the the two component without trying to merge any external ids from target component. 
3. It will fail to load 'confirm' page and there is an error 
`com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of java.lang.String out of START_ARRAY token`

Issue 2:
1. Try to merge two components without selecting all the external ids.
2. It will merge all the externalIds from target componnent. 
3. It should only merge the selected externalIds and additional data.

**Comment by lepokle** [comment]
I've rebased and improved the error handling. However I was not able to reprodue the issues.

@nutanv1contr Might you please describe step by step in more detail to reproduce the issue? I tried to follow your steps above but it worked like expected.

**Comment by nutanv1contr** [comment]
Tested the PR again. Functionality is working as expected now. 

1.  Created two components with external id and additional data associated and merged successfully.
2.  Selected external ids and additional data  are appearing along with existing records. 
3. If no external ids or additional data is selected from source component then only the records from target component are appearing.

**Comment by nutanv1contr** [comment]
Tested the PR again with above mentioned scenarios again. Functionality is working as expected.
Code looks good.

**Pull request merged**
