### PR TITLE
feat(OAuthClient): Create, update, delete OAuthClient from UI

### LINKED ISSUE #1135: Add new Page in Admin section , to list, create, delete REST api client details.
Admin user should be able to create/view/delete Client details from UI.

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*#1135*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: closes #1135 

Capture2
Capture

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by smrutis1** [comment]
One Remark:
---------------
1)  Can the create button be removed (if there is no use) after displaying the client information.
image

**Comment by JaideepPalit** [comment]
Thanks for review and test.
Based on previous discussion
- Removed Create button , added OK button
- Added copy to clipboard button

oa

**Review by smrutis1 — APPROVED** [review]
Code looks good to me. Tested Successfully as well.

**Comment by zhangjingcat** [comment]
Hi @JaideepPalit , where can we get the plugin  Private_Pages_7_3_3_GA4.lar and how to import that plugin? Thank you very much!

**Comment by zhangjingcat** [comment]
> Hi @JaideepPalit , where can we get the plugin Private_Pages_7_3_3_GA4.lar and how to import that plugin? Thank you very much!

I found the documents now , thanks!

**Pull request merged**
