### PR TITLE
feat(rest): new param (allDetails) added in component call to get more details of component

### LINKED ISSUE #1719: REST API: component call should have an allDetails parameter
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

component call should have an allDetails parameter like releases and projects.

### PR DESCRIPTION
**Pull request by muhammadali9699**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> allDetails parameter added in component call like project and releases.
> 
> * Which issue is this pull request belonging to and how is it solving it? (*#1719*)
> * Did you add or update any new dependencies that are required for your change?

Issue: closes #1719 

### Checklist
Must:
- [X ] All related issues are referenced in commit messages and in PR

Signed-off-by: Muhammad Ali <alimuhammad@siemens.com>

### CODE REVIEW

**Comment by nikkuma7** [comment]
test successfull.
image

**Review by KoukiHama — COMMENTED** [review]
codes are ok

**Comment by KoukiHama** [comment]
@muhammadali9699 
please follow this  semantic commit message

 https://www.eclipse.org/sw360/docs/development/dev-semantic-commits/#example-of-semantic-commit-message

**Review by KoukiHama — CHANGES_REQUESTED** [review]
commit message are not semantic

**Review by KoukiHama — APPROVED** [review]

**Comment by KoukiHama** [comment]
i checked new commit  message and it is ok.

**Pull request merged**
