### PR TITLE
fix(upgradeVersion):Upgrade version.

### PR DESCRIPTION
**Pull request by ravi110336**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> **It is recommended to upgrade some existing software version which sw360 is currently using as part of the technical debt.**
> * Which issue is this pull request belonging to and how is it solving it? (#1202 #1203 #1204 #1205 #1206 #1207)
> * Did you add or update any new dependencies that are required for your change? No

Issue: closes (#1202 #1203 #1204 #1205 #1206 #1207)

- First install the Thrift 0.14 
- Do a mvn clean install without skipping any test cases 
- Test the application end to end from the UI and REST end.
> Have you implemented any additional tests? No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: ravi110336 <kumar.ravindra@siemens.com>

### CODE REVIEW

**Comment by JaideepPalit** [comment]
- Fixed failing test case for authorization-server.
- Testcase for resource-server needs to be fixed

**Comment by ravi110336** [comment]
- Fixed the test cases for resource server while generating the rest docs from the payload xml.

**Comment by smrutis1** [comment]
* Fixed the build issue post upgrading the properties as per Spring 2.X , build is successful now.
* Updated the REST documentation for failing health API.
* Fixed indentation in some of the test cases.

**Comment by ravi110336** [comment]
Tested the below in local and seems to work fine:
- Different flow for the UI in Project, Component and Release to see all the views, edit update and delete.
- Generate the new Rest Docs after changing the  code with the new jUnit attributes.

**_Not Working:_**
The Rest API is throwing the 404 error for any request, in spring boot 2 version something has changed and seems it is not able to find the endpoints with the current requestMapping/configuration.

image

**Comment by smrutis1** [comment]
Have fixed the `404` issue

**Comment by ravi110336** [comment]
Tested some REST API, its working fine for GET, PATCH, DELETE and POST request.

GET:
http://localhost:8080/resource/api/projects?allDetails=true&page=0&page_entries=5&sort=name%2Cdesc
http://localhost:8080/resource/api/projects?page=0&page_entries=5&sort=name%2Cdesc

PATCH:
http://localhost:8080/resource/api/vulnerabilities/987

DELETE:
http://localhost:8080/resource/api/vulnerabilities/987

POST:
http://localhost:8080/resource/api/vulnerabilities/44835/releaseVulnerabilityRelation

**Comment by smrutis1** [comment]
Resolved merge conflicts

**Comment by smrutis1** [comment]
Observed few issues while giving a test in our stage instance with large datasets.
1. Projects not loading.  [ThriftError.txt](https://github.com/eclipse/sw360/files/6928899/ThriftError.txt)

2. OAuth Client management page is not opening.

**Comment by ravi110336** [comment]
- Tested the below use cases in stage environment for both UI and Rest API and seems to work fine.
**UI:**
open all views 
create new project 
create attachment at new project (any file) 
approve this attachment 
create new release
download attachment 
Search Project/Component 
Add Attachment to a component
Delete attachment to a component
Download attachment to a component
Create a release
Add Attachment to release 
Download/Delete attachment 
Generate License Info
Create Clearing Request/Approve Clearing Request

  **Rest API:**

_For Projects:_ 
GET: https://stage.sw360.siemens.com/resource/api/projects/17e650e74a824728a58521abd8fa688e/attachments
GET: https://stage.sw360.siemens.com/resource/api/projects/17e650e74a824728a58521abd8fa688e
PATCH: https://stage.sw360.siemens.com/resource/api/projects/17e650e74a824728a58521abd8fa688e
POST: https://stage.sw360.siemens.com/resource/api/projects/17e650e74a824728a58521abd8fa688e/releases

_For Components:_
GET:https://stage.sw360.siemens.com/resource/api/componentsname=TestRESTAPI&page=0&page_entries=5&sort=name%2Cdesc
POST: https://stage.sw360.siemens.com/resource/api/components/fa4151a0c17045f7a37a6424a9cd7a33/attachments
GET: https://stage.sw360.siemens.com/resource/api/components/fa4151a0c17045f7a37a6424a9cd7a33/attachments
DELETE:https://stage.sw360.siemens.com/resource/api/components/fa4151a0c17045f7a37a6424a9cd7a33/attachments/9e0d43b3f2934d0eb1d9ede2588e6c1e
PATCH: https://stage.sw360.siemens.com/resource/api/components/5b01a82e88184ec98859d7bb20661c73
DELETE: https://stage.sw360.siemens.com/resource/api/components/5b01a82e88184ec98859d7bb20661c73

_For Releases:_
GET: https://stage.sw360.siemens.com/resource/api/releases?page=0&page_entries=5&sort=name%2Cdesc
POST: https://stage.sw360.siemens.com/resource/api/releases/92b4e5f788af455b9e85d651774bfbea/attachments
POST: https://stage.sw360.siemens.com/resource/api/releases

_For Attachments:_
GET: https://stage.sw360.siemens.com/resource/api/attachments/9e0d43b3f2934d0eb1d9ede2588e6c1e

_For Licenses:_
GET: https://stage.sw360.siemens.com/resource/api/licenses

_For vulnerabilities:_
GET: https://stage.sw360.siemens.com/resource/api/vulnerabilities

- one observation is the **Rest API Docs** are not coming correctly but that may be the issue with the build because it is listing all the details correctly in local when i gave the clean build.

**Comment by mcjaeger** [comment]
(from discussion) access to the private project needs to be tested

**Comment by smrutis1** [comment]
project visibility(private project) works fine. However there is an issue with projects count for `Show All` in projects listing page

image

**Comment by smrutis1** [comment]
Have resolved the issue mentioned with the counts

**Review by JaideepPalit — CHANGES_REQUESTED** [review]
Reviewed files ` backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectRepository.java  and frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java`

Seems to be some logical error -

**Issue 1 -** Goto Last Page. Result - `Showing 7,831 to 7,831 of 7,831 entries` with different no of projects based on sort column, max size of page. No Search Params used.




**Issue 2 -** Pagination error - Search with some fields like in screenshot. Result show 7831 entries. Should be 3 entries 




**Issue 3 -** Seems to be some issue with sorting. Example - sort by name ascending.
**_Page -12_** 


**_Page 13_**


Sort By Description Descending
sorting_byDesc_decending

**Issue 4 -** Shows more than 10 records. Sort by Project responsible multiple times in Page 1. Jump to Page 5.
moreThan10Result

**Review by JaideepPalit — APPROVED** [review]
Code looks ok to me

**Comment by mcjaeger** [comment]
brnach was tested also on a clone of a productive instance

**Pull request merged**
