### PR TITLE
chore(logging): upgrade logging to log4j2

### PR DESCRIPTION
**Pull request by oheger-bosch**
This PR updates the logging framework from log4j 1.x to log4j2. The logging output should not be affected by this change.

The dependencies to log4j1 have been replaced by corresponding dependencies to log4j2; for some transitive dependencies to log4j1 explicit excludes have been added. With additional dependencies, it is made sure that log output produced by other libraries (slf4j or commons-logging) is routed to and processed by log4j2.

While the log methods have not changed in the new version, the way how to obtain a logger is now different; also the logger classes have been moved to another package. Therefore, all the Java classes that make use of a logger had to be (slightly) adapted. The logging API allows generating strings based on templates with placeholders. This helps to improve performance as string concatenations are done only if the log event actually can be output. In two or three files that I have modified, I made use of this feature, but doing this more globally would require a lot of more effort.

An initial XML-based configuration file for log4j2 has been added. It should be mainly equivalent to the existing configuration. The configuration could be enhanced later, e.g. to make use of advanced features like asynchronous logging. The properties files to configure log4j1 have been removed.

Note that this PR does not upgrade to the most recent version of log4j2. There is, unfortunately, an incompatibility of the Spring boot version in use with log4j2 versions greater than 2.7. More information can be found [here](https://stackoverflow.com/questions/50680649/log4j2-unrecognized-conversion-specifier-xwex-starting-at-position-160-in-co) and in [this ticket](https://github.com/spring-projects/spring-boot/issues/9172).

Issue: 
https://github.com/eclipse/sw360/issues/618

### CODE REVIEW

**Comment by mcjaeger** [comment]
testing: maybe problem with my artefact configuration, need to check:
```
org.osgi.framework.BundleException: Could not resolve module: sw360-datahandler [1077]_  Unresolved requirement: Import-Package: org.apache.logging.log4j; version="[2.7.0,3.0.0)"_ [Sanitized]
```

**Comment by oheger-bosch** [comment]
I can now reproduce the problem with the unresolved requirement in SW360chores. Will have to dig into it. Obviously, the bundles for log4j2 are not correctly deployed in the OSGi container.

Do you have any hint for me whether bundles need to be treated in a special way during the build process?

**Comment by oheger-bosch** [comment]
Okay, I was able to fix the problem by adding the missing bundles for logging to liferay in the SW360chores project. So I guess I will have to create antoher pull request against that project.

**Comment by mcjaeger** [comment]
unfortunately, result from clean vagrant built:
```
2020-06-24 08:54:50.625 ERROR [fileinstall-/opt/liferay-ce-portal-7.2.1-ga2/osgi/modules][LogService:93] Error while starting bundle: file:/opt/liferay-ce-portal-7.2.1-ga2/osgi/modules/org.eclipse.sw360.importers-8.3.0-SNAPSHOT.jar 
org.osgi.framework.BundleException: Could not resolve module: sw360-importers [1079]_  Unresolved requirement: Import-Package: org.apache.logging.log4j; version="[2.7.0,3.0.0)"_ [Sanitized]
```

**Comment by mcjaeger** [comment]
@oheger-bosch so we can close this PR? Actually I am confused because the bundle-setup should be independent from chores. I think you need to setup exported package and imported package at the same time.

**Comment by oheger-bosch** [comment]
@mcjaeger: It may well be the case that my understanding of the whole SW360 setup is still limited, so please bear with me.

As far as I understand it, SW360 runs on a Tomcat server with a Liferay that needs some special preparations. For instance, some helper libraries needed by the SW360 portal bundles, such as commons-io or guava, need to be added as modules to Liferay. As log4j2 is now a new dependency of these bundles, the corresponding jars have to be made available as modules in the same way. (I have to admit that I don't know how this was working with log4j 1; maybe this framework is also used by Liferay and therefore available out of the box?) 

The PR against SW360chores now extends the Liferay deployment by the required modules. When you do your tests, how do you setup and deploy SW360? Is your deployment based on SW360chores? In any case, the bundles for log4j2 need to be added somehow to Liferay, so that they can be picked up by the portal bundles.

**Comment by mcjaeger** [comment]
It runs in Tomcat, but inside the Tomcat another layer of OSGi has been added. Liferay is a servlet application, internally structured as OSGi bundles. As such, everything which is used by the LIferay such as portlets shall be an OSGI bundle. This cleans up class loading (among other things), here some graphic:

https://help.liferay.com/hc/en-us/articles/360018168551-Liferay-Portal-Classloader-Hierarchy

This means if you compile source code and put the dependecy log4j into the maven: fine for compile and package. But it is not container automatically in an OSGi bundle unless you declare it in the *.bnd file

**Comment by mcjaeger** [comment]
ah, and I do the tests using vagrant, so everything should be fine with doing just:
```
    mvn package -P deploy -Dbase.deploy.dir=. -Dliferay.deploy.dir=${LIFERAY_INSTALL}/deploy -Dbackend.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.17/webapps -Drest.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.17/webapps $mavenParameters
```

**Comment by oheger-bosch** [comment]
Is this the vagrant setup from the SW360chores project or a different one?

I found this [article](https://help.liferay.com/hc/en-us/articles/360017889652-Implementing-Logging-) about logging in Liferay. It explains why log4j 1 works directly, as this framework is actually used by Liferay under the hood. (However, they consider this as an implementation detail which might change in future; so the recommendation is using Slf4j as a facade rather than accessing log4j loggers directly.)

As there is already a logging infrastructure in place for Liferay, it may be best to use it rather than deploying another logging framework. So I could revert the changes in the frontend classes. A drawback would be that then different logging approaches are used by different parts of the SW360 codebase.

Alternatively, we could switch to Slf4j everywhere (it is already used by some source files). The backend would use log4j2 as underlying implementation, while the frontend would continue using the native Liferay logging. WDYT?

**Comment by smrutis1** [comment]
Just tested it in my local machine with native installation. The similar issues as mentioned https://github.com/eclipse/sw360/pull/878#issuecomment-648657586 here are appearing.

**Comment by oheger-bosch** [comment]
Found a solution that could be verified against an sw360chores installation without the need to modify the setup. (So [this PR](https://github.com/sw360/sw360chores/pull/76) is no longer needed.)

A new module has been introduced under _libraries_ which generates an OSGi bundle containing the required log4j2 libraries. Like the other OSGi bundles in the project, it is copied into the Liferay deploy folder by the deploy profile. If this bundle is present, the logging classes can be resolved by the SW360 OSGi bundles.

The only thing I noticed was that during the first restart of SW360 after applying these changes Liferay still generated lots of exceptions regarding NoClassDefFound errors, but those disappeared on succeeding restarts, and everything was working fine. So if you see these exceptions in the log while testing, give it a second try.

**Comment by mcjaeger** [comment]
@oheger-bosch I am sorry, merging the couchdb has created a conflict. Would you be able to rebase it?

**Comment by oheger-bosch** [comment]
Rebased on master.

Interestingly, I get some test failures in the src-common project afterwards (see below). Any idea what could be the cause? The build on travis is obviously not affected.

```
Running org.eclipse.sw360.spdx.SpdxBOMImporterTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.549 sec <<< FAILURE!
testProject(org.eclipse.sw360.spdx.SpdxBOMImporterTest)  Time elapsed: 0.316 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
	at com.ibm.icu.impl.UPropertyAliases.<clinit>(UPropertyAliases.java:87)
	at com.ibm.icu.lang.UCharacter.<clinit>(UCharacter.java:5680)
	at com.hp.hpl.jena.rdf.arp.impl.CharacterModel.isComposingChar(CharacterModel.java:134)
	at com.hp.hpl.jena.rdf.arp.impl.ParserSupport.checkComposingChar(ParserSupport.java:140)
	at com.hp.hpl.jena.rdf.arp.states.AbsWantLiteralValueOrDescription.characters(AbsWantLiteralValueOrDescription.java:46)
	at com.hp.hpl.jena.rdf.arp.states.WantLiteralValueOrDescription.characters(WantLiteralValueOrDescription.java:65)
	at com.hp.hpl.jena.rdf.arp.impl.XMLHandler.characters(XMLHandler.java:163)
	at org.apache.xerces.parsers.AbstractSAXParser.characters(Unknown Source)
	at org.apache.xerces.impl.XMLNamespaceBinder.characters(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.hp.hpl.jena.rdf.arp.impl.RDFXMLParser.parse(RDFXMLParser.java:142)
	at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:158)
	at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:145)
	at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:215)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:226)
	at org.spdx.rdfparser.SPDXDocumentFactory.createSpdxDocument(SPDXDocumentFactory.java:113)
	at org.eclipse.sw360.spdx.SpdxBOMImporter.openAsSpdx(SpdxBOMImporter.java:98)
	at org.eclipse.sw360.spdx.SpdxBOMImporter.importSpdxBOM(SpdxBOMImporter.java:52)
	at org.eclipse.sw360.spdx.SpdxBOMImporter.importSpdxBOMAsProject(SpdxBOMImporter.java:46)
	at org.eclipse.sw360.spdx.SpdxBOMImporterTest.testProject(SpdxBOMImporterTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
	at com.ibm.icu.util.VersionInfo.getInstance(VersionInfo.java:188)
	at com.ibm.icu.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
	at com.ibm.icu.impl.ICUDebug.<clinit>(ICUDebug.java:69)
	... 59 more

testRelease(org.eclipse.sw360.spdx.SpdxBOMImporterTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.ibm.icu.lang.UCharacter
	at com.hp.hpl.jena.rdf.arp.impl.CharacterModel.isComposingChar(CharacterModel.java:134)
	at com.hp.hpl.jena.rdf.arp.impl.ParserSupport.checkComposingChar(ParserSupport.java:140)
	at com.hp.hpl.jena.rdf.arp.states.AbsWantLiteralValueOrDescription.characters(AbsWantLiteralValueOrDescription.java:46)
	at com.hp.hpl.jena.rdf.arp.states.WantLiteralValueOrDescription.characters(WantLiteralValueOrDescription.java:65)
	at com.hp.hpl.jena.rdf.arp.impl.XMLHandler.characters(XMLHandler.java:163)
	at org.apache.xerces.parsers.AbstractSAXParser.characters(Unknown Source)
	at org.apache.xerces.impl.XMLNamespaceBinder.characters(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.hp.hpl.jena.rdf.arp.impl.RDFXMLParser.parse(RDFXMLParser.java:142)
	at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:158)
	at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:145)
	at com.hp.hpl.jena.rdf.arp.JenaReader.read(JenaReader.java:215)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:226)
	at org.spdx.rdfparser.SPDXDocumentFactory.createSpdxDocument(SPDXDocumentFactory.java:113)
	at org.eclipse.sw360.spdx.SpdxBOMImporter.openAsSpdx(SpdxBOMImporter.java:98)
	at org.eclipse.sw360.spdx.SpdxBOMImporter.importSpdxBOM(SpdxBOMImporter.java:52)
	at org.eclipse.sw360.spdx.SpdxBOMImporter.importSpdxBOMAsRelease(SpdxBOMImporter.java:41)
	at org.eclipse.sw360.spdx.SpdxBOMImporterTest.testRelease(SpdxBOMImporterTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

**Comment by mcjaeger** [comment]
@oheger-bosch maybe it is an Internet connectivity issue ...

**Comment by mcjaeger** [comment]
@oheger-bosch I have the compilation error too, and for sure my mchine is OK with Internet. Let's leave it aside for now and fix it later ...

**Comment by mcjaeger** [comment]
I am not sure to see what version is actually running, but I guess if it like this:

```
siemagrant@ubuntu-xenial:/opt/liferay-ce-portal-7.2.1-ga2$ find | grep log4j
./osgi/state/org.eclipse.osgi/1082/0/.cp/WEB-INF/lib/log4j-slf4j-impl-2.7.jar
./osgi/state/org.eclipse.osgi/1082/0/.cp/WEB-INF/lib/log4j-jcl-2.7.jar
./osgi/state/org.eclipse.osgi/1082/0/.cp/WEB-INF/lib/log4j-api-2.7.jar
./osgi/state/org.eclipse.osgi/1082/0/.cp/WEB-INF/lib/log4j-core-2.7.jar
./osgi/state/org.eclipse.osgi/1080/0/.cp/log4j-1.2-api-2.7.jar
./osgi/state/org.eclipse.osgi/1080/0/.cp/log4j-api-2.7.jar
./osgi/state/org.eclipse.osgi/1080/0/.cp/log4j-core-2.7.jar
./osgi/state/org.eclipse.osgi/73/0/.cp/lib/log4j-api-2.11.2.jar
./osgi/state/org.eclipse.osgi/73/0/.cp/lib/log4j-core-2.11.2.jar
./osgi/modules/org.eclipse.sw360.log4j-osgi-support-11.0.0-SNAPSHOT.jar
./tomcat-9.0.17/webapps/changelogs/WEB-INF/classes/log4j2.xml
./tomcat-9.0.17/webapps/changelogs/WEB-INF/lib/log4j-1.2-api-2.7.jar
./tomcat-9.0.17/webapps/changelogs/WEB-INF/lib/log4j-slf4j-impl-2.7.jar
./tomcat-9.0.17/webapps/changelogs/WEB-INF/lib/log4j-jcl-2.7.jar
./tomcat-9.0.17/webapps/changelogs/WEB-INF/lib/log4j-api-2.7.jar
./tomcat-9.0.17/webapps/changelogs/WEB-INF/lib/log4j-core-2.7.jar
./tomcat-9.0.17/webapps/schedule/WEB-INF/classes/log4j2.xml
```

it should be OK?

**Pull request merged**
