### PR TITLE
fix(rest): GET /{resources} response will contain all resources if there are no paging parameters in the request

### PR DESCRIPTION
**Pull request by hengel2810**
This PR will remove the default paging if there are no paging parameters in the `GET /{resources}` request.

### CODE REVIEW

**Comment by mcjaeger** [comment]
(from discussion) seems not to be limited to components (opposed to what the title suggests)

**Comment by hengel2810** [comment]
Sorry about the misleading title. This PR removes the default paging for all resource lists generated by the `ResourceListController`. At the moment it only concerns `Components` but in future implementations it will also concern other resources. I've updated the PR.

**Comment by maierthomas** [comment]
test result:

1. 'GET' /resource/api/components = all components are visible, without pagination parameters
2. 'GET' /resource/api/components?page=1&page_entries=5&sort=name,desc = all components are visible, with pagination parameters.

I think something is wrong, because in the 2. example I receive all components while I set the pagination parameters (page=1 and page_entries=5).

See my test result:

image

**Comment by hengel2810** [comment]
I've updated the PR, the problem should be fixed now.

**Comment by maierthomas** [comment]
@hengel2810 please sqash these 2 commits into 1. thank you.

**Comment by hengel2810** [comment]
@maierthomas commits are updated

**Comment by maierthomas** [comment]
tested successfully.

- Without pagination parameters = All values are visible
- /resource/api/components?page=1&page_entries=5&sort=name,desc = only 5 components are visible

**Pull request merged**
