### PR TITLE
feat(licenses): allow to create unchecked licenses

### LINKED ISSUE #190: Allow checked/unchecked state of Licenses
<a href="https://github.com/bs-jokri"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Friday Nov 10, 2017 at 18:31 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/679_

----

It should be possible to have licenses associated with a state that indicates whether this license is already gone through a clearing process. (Is required to mark licenses imported from other sources such as BDP)

### PR DESCRIPTION
**Pull request by maxhbr**
This allows everyone to create licenses, but the created licenses are marked as unchecked.

Since there is no owner concept on licenses, everyone is able to modify every unchecked license, and no moderation requests are generated.

closes #190

### CODE REVIEW

**Comment by maxhbr** [comment]
I will look into the failing test

**Comment by maxhbr** [comment]
@kallesoranko : thanks for the code review

**Comment by adrian-evo** [comment]
Tested and unchecked licenses can be created and then modified by admin.

**Comment by maierthomas** [comment]
@maxhbr rebase onto master to merge this PR. :+1:  thanks

**Comment by maxhbr** [comment]
@maierthomas this PR is now rebased

**Pull request merged**
