### PR TITLE
Avoids key error in migration script 048

### PR DESCRIPTION
**Pull request by dineshr93**
To avoid this error

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

This pull request resolves this issue https://github.com/eclipse/sw360/issues/1821#issue-1565917274  in the migrationscript 048
Issue: 

### Suggest Reviewer
@KoukiHama

### CODE REVIEW

**Comment by KoukiHama** [comment]
I will check it next week.

**Comment by KoukiHama** [comment]
codes are ok.

**Comment by KoukiHama** [comment]
Please refer to the following and update again.

https://www.eclipse.org/sw360/docs/development/dev-semantic-commits/

**Comment by dineshr93** [comment]
Hi @KoukiHama   I created new pull request https://github.com/eclipse/sw360/pull/1829

**Pull request closed without merging**
