### PR TITLE
feat(rest): Added filter for get project vulnerabilities endpoint

### PR DESCRIPTION
**Pull request by smrutis1**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

* Added filter based on priorities and project relevance and respective documentation for `projects/{id}/vulnerabilities`
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*) 
> * Did you add or update any new dependencies that are required for your change? - No

Issue: NA

### How To Test?

* Need to test the REST endpoint (`projects/{id}/vulnerabilities?priority=xxxx` & `projects/{id}/vulnerabilities?projectRelevance=yyyy`)

> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

### CODE REVIEW

**Review by JaideepPalit — CHANGES_REQUESTED** [review]
Some Review comments.
- Since `priority` filter is multivalued filter separated by comma. It would be good to indicate it in Doc.
- Is it possible to have list of possible values for `priority and relevance` in Doc.

**Comment by smrutis1** [comment]
Thanks @JaideepPalit for review. Have made respective changes in the doc.

**Review by JaideepPalit — APPROVED** [review]
Code and Documentation looks fine to me.
Needs general test with vulnerability data.

**Review by JaideepPalit — APPROVED** [review]
Tested successfully with dummy data provided by @smrutis1

**Pull request merged**
