### PR TITLE
fix(DBTestsFail): Migrating databasetest.properties to couchdb-test.properties.

### PR DESCRIPTION
**Pull request by ravi110336**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> 

- Migrating the databasetest.properties to couchdb-test.properties.

> * Which issue is this pull request belonging to and how is it solving it? (*#1333*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #1333 

   
**_Note:_** 
After successful testing the PR, in productive we need to remove the databasetest.properties and update the couchdb-test.properties inside etc/sw360.
- Remove the databasetest.properties. 
- use the couchdb-test.properties.
- Give a clean maven build without skipping any test cases.
- Test the SW360 application, if everything works fine and connects with the couch DB without any issue.

 couchdb-test.properties file:
**couchdb-test.properties**
couchdb.url = http://localhost:5984
couchdb.user = admin
couchdb.password = xxxxxx
couchdb.database = sw360_test_db
couchdb.usersdb = sw360_test_users
couchdb.attachments = sw360_test_attachments
couchdb.fossologyKeys = sw360_test_fossologykeys
couchdb.vulnerability_management = sw360_test_vm

> Have you implemented any additional tests? No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR
Signed-off-by: ravi110336 <kumar.ravindra@siemens.com>

### CODE REVIEW

**Comment by ravi110336** [comment]
As per discussion, removed the database "**datahandlertestdb**" and used the database: "**sw360_test_users**" from the couchdb-test.properties.

**Comment by smrutis1** [comment]
Code looks ok to me. However kindly rebase and push to check if the ci is passing.

**Comment by ravi110336** [comment]
Hi @smrutis1 , thanks for the review, The CI build was failing because the couchdb-test.properties was not present in the libraries/lib-datahandler/src/test/resources/ directory, i have removed the databasetest.properties and added the couchdb-test.properties file, as per the githubactions.yml file changes.

**Comment by smrutis1** [comment]
May be please try to refer the existing one  `build-configuration/test-resources/couchdb-test.properties` instead of creating a new one

**Comment by ravi110336** [comment]
Thanks @smrutis1, referred the existing path **build-configuration/test-resources/couchdb-test.properties.**

**Review by smrutis1 — APPROVED** [review]
Code looks ok to me.

**Pull request merged**
