### PR TITLE
feat(docs): relicensing from EPL-1.0 to EPL-2.0

### PR DESCRIPTION
**Pull request by mcjaeger**
The long-awaited relicensing effort which should lead to SW360 7.0 release.

Change basically, from Eclipse Public License 1.0 to Eclipse Public License 2.0.

This has involved a number of other changes:

* some files had EDL-1.0 license header text but SPDX identifier of EPL-1.0
* changed formatting here and there to make it looking nicer
* changes the check for licenses script that checks for the files

### CODE REVIEW

**Comment by mcjaeger** [comment]
... hmpf: now also the `.travis/testForLicenseHeaders.sh`executes also successfully on my machine.

**Comment by mcjaeger** [comment]
yeay, ultimately, the test for licenses is green!

**Comment by sweetca** [comment]
related changes and looks good to me 👍

**Comment by lixiaoming2099** [comment]
OK with relicensing

**Comment by arunazhakesan** [comment]
> The long-awaited relicensing effort which should lead to SW360 7.0 release.
> 
> Change basically, from Eclipse Public License 1.0 to Eclipse Public License 2.0.
> 
> This has involved a number of other changes:
> 
> * some files had EDL-1.0 license header text but SPDX identifier of EPL-1.0
> * changed formatting here and there to make it looking nicer
> * changes the check for licenses script that checks for the files

OK from me and Siemens Healthineers side!

**Pull request merged**
