### PR TITLE
fix(ModerationRequests): Updated views with queries

### LINKED ISSUE #1271: Moderation requests not loading for large datasets
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

We observed moderation requests does not load(DB views breaks) for large number of requests(>15000)
 

### Versions

* Last commit id on master: b94104795bfb7ff7d46bc88de9f619f4fc77d683
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### Couchdb logs
```[error] 2021-06-13T15:22:05.657650Z couchdb@127.0.0.1 <0.28088.868> -------- OS Process Error <0.31264.757> :: {<<"InternalError">>,{[{<<"message">>,<<"allocation size overflow">>},{<<"fileName">>,<<"./share/server/main.js">>},{<<"lineNumber">>,1518},{<<"stack">>,<<"([object Object])@./share/server/main.js:1518\n()@./share/server/main.js:1667\n()@./share/server/main.js:1688\n@./share/server/main.js:1\n">>}]}}
[error] 2021-06-13T15:22:05.658307Z couchdb@127.0.0.1 <0.24149.868> d0da0b71d1 rexi_server: from: couchdb@127.0.0.1(<0.26287.868>) mfa: fabric_rpc:map_view/5 throw:{<<"InternalError">>,{[{<<"message">>,<<"allocation size overflow">>},{<<"fileName">>,<<"./share/server/main.js">>},{<<"lineNumber">>,1518},{<<"stack">>,<<"([object Object])@./share/server/main.js:1518\n()@./share/server/main.js:1667\n()@./share/server/main.js:1688\n@./share/server/main.js:1\n">>}]}} [{couch_mrview_util,get_view_index_state,5,[{file,"src/couch_mrview_util.erl"},{line,138}]},{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,82}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,262}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,138}]}]
[error] 2021-06-13T15:22:05.658613Z couchdb@127.0.0.1 <0.26287.868> d0da0b71d1 req_err(3722911048) InternalError : {[{<<"message">>,<<"allocation size overflow">>},
  {<<"fileName">>,<<"./share/server/main.js">>},
  {<<"lineNumber">>,1518},
  {<<"stack">>,
   <<"([object Object])@./share/server/main.js:1518\n()@./share/server/main.js:1667\n()@./share/server/main.js:1688\n@./share/server/main.js:1\n">>}]}
    [<<"couch_mrview_util:get_view_index_state/5 L138">>,<<"couch_mrview_util:get_view/4 L82">>,<<"couch_mrview:query_view/6 L262">>,<<"rexi_server:init_p/3 L138">>]
[notice] 2021-06-13T15:22:05.658918Z couchdb@127.0.0.1 <0.26287.868> d0da0b71d1 localhost:5984 127.0.0.1 admin GET /sw360db/_design/ModerationRequest/_view/closedRequestsBymoderators?include_docs=true&startkey=%5B%22smruti.sahoo@siemens.com%22,%22%EF%BF%B0%22%5D&endkey=%5B%22smruti.sahoo@siemens.com%22%5D&limit=11&descending=true 500 ok 3271
[error] 2021-06-13T15:22:05.659048Z couchdb@127.0.0.1 emulator -------- Error in process <0.28088.868> on node 'couchdb@127.0.0.1' with exit value:
{{nocatch,{<<"InternalError">>,{[{<<"message">>,<<"allocation size overflow">>},{<<"fileName">>,<<"./share/server/main.js">>},{<<"lineNumber">>,1518},{<<"stack">>,<<"([object Object])@./share/server/main.js:1518\n()@./share/server/main.js:1667\n()@./share/server/main.js:1688\n@./share/server/main.js:1\n">>}]}}},[{couch_os_process,prompt,2,[{file,"src/couch_os_process.erl"},{line,59}]},{couch_query_servers,map_doc_raw,2,[{file,"src/couch_query_servers.erl"},{line,68}]},{couch_mrview_updater,'-map_docs/2-fun-0-',3,[{file,"src/couch_mrview_updater.erl"},{line,165}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{couch_mrview_updater,map_docs,2,[{file,"src/couch_mrview_updater.erl"},{line,172}]}]}

[error] 2021-06-13T15:22:05.659282Z couchdb@127.0.0.1 <0.8561.868> 4191f233e9 rexi_server: from: couchdb@127.0.0.1(<0.27518.868>) mfa: fabric_rpc:map_view/5 throw:{<<"InternalError">>,{[{<<"message">>,<<"allocation size overflow">>},{<<"fileName">>,<<"./share/server/main.js">>},{<<"lineNumber">>,1518},{<<"stack">>,<<"([object Object])@./share/server/main.js:1518\n()@./share/server/main.js:1667\n()@./share/server/main.js:1688\n@./share/server/main.js:1\n">>}]}} [{couch_mrview_util,get_view_index_state,5,[{file,"src/couch_mrview_util.erl"},{line,138}]},{couch_mrview_util,get_view,4,[{file,"src/couch_mrview_util.erl"},{line,82}]},{couch_mrview,query_view,6,[{file,"src/couch_mrview.erl"},{line,262}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,138}]}]
[error] 2021-06-13T15:22:05.659724Z couchdb@127.0.0.1 <0.27518.868> 4191f233e9 req_err(3722911048) InternalError : {[{<<"message">>,<<"allocation size overflow">>},
  {<<"fileName">>,<<"./share/server/main.js">>},
  {<<"lineNumber">>,1518},
  {<<"stack">>,
   <<"([object Object])@./share/server/main.js:1518\n()@./share/server/main.js:1667\n()@./share/server/main.js:1688\n@./share/server/main.js:1\n">>}]}
    [<<"couch_mrview_util:get_view_index_state/5 L138">>,<<"couch_mrview_util:get_view/4 L82">>,<<"couch_mrview:query_view/6 L262">>,<<"rexi_server:init_p/3 L138">>]
[notice] 2021-06-13T15:22:05.659914Z couchdb@127.0.0.1 <0.27518.868> 4191f233e9 localhost:5984 127.0.0.1 admin GET /sw360db/_design/ModerationRequest/_view/openRequestsBymoderators?include_docs=true&startkey=%5B%22smruti.sahoo@siemens.com%22,%22%EF%BF%B0%22%5D&endkey=%5B%22smruti.sahoo@siemens.com%22%5D&limit=11&descending=true 500 ok 3272`
Logs generated under /var/log/sw360/sw360.log

### PR DESCRIPTION
**Pull request by smrutis1**
Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

Replaced the views with mango queries.

> * Which issue is this pull request belonging to and how is it solving it? (*#1271*)
> * Did you add or update any new dependencies that are required for your change?

Issue: Closes #1271 

* load requests tab with large number of requests.
* Search moderation requests.
* Raise a moderation request.
* Accept/Decline the moderation request.
> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by mcjaeger** [comment]
actually tested on our stage instance ...

**Comment by smrutis1** [comment]
Fixed the problem with show "All"

**Review by JaideepPalit — COMMENTED** [review]
Code looks fine to me.
However the travis ci is not running.
image

**Comment by mcjaeger** [comment]
tested tests with sw360vagrant

**Pull request merged**
