### PR TITLE
yet another try: chore(java): migrating to openjdk java version 11

### LINKED ISSUE #400: Does SW360 work with openjdk > 8 ?
We should think about whether SW360 can be compiled or executed with a openjdk version greater than 8

### PR DESCRIPTION
**Pull request by mcjaeger**
Signed-off-by: Michael C. Jaeger <michael.c.jaeger@siemens.com>

So this is basically, to have a branch that will work with the new sw360vagrant PR which changes to bionic (Ubuntu 18.04) including a number of resulting version updates

* thrift 0.13
* couchdb 2.1.2
* Java 11
* postgresql 10
* smaller bumps, not really relevant for sw360 

Please see new PR at: https://github.com/sw360/sw360vagrant/pulls (upcoming)

For this project New dependencies:
* Java 11
* Lombok 1.18.2
* javax.annotations-api 1.3.2
* thrift 0.13

### Suggest Reviewer

anyone could review and test the application

### How To Test?

Just do a `mvn clean install` ....

closes #400

### CODE REVIEW

**Comment by mcjaeger** [comment]
the main problem is that updating to java requirs substantial updates to the Spring stack:
* Spring at least 5.1 (current patch level 5.1.16)
* Spring boot at least 2.1 (current patch level 2.1.15)
* Spring Rest docs 2.0.5 - milestone for Java 11 support not released yet!

Open are how to pin dependencies for Spring Security - the entire REST stack is not working at all, according to tests.

Background: After Java 8, some (java) packages are dropped from release to release of Java and require a manual pull in of the dependency packages. Unfortunately not only for our projects but also for the dependencies. If a dependecy is not compatible with Java 11 -> we re blocked. looks like for Spring rest docs this is the case right now.

**Comment by JaideepPalit** [comment]
Fixed deployment issue

- Current liferay version `liferay-ce-portal-7.2.1-ga2` is compatible till `openjdk 11.0.5`.
  **Reference**
  - Ref - https://liferay.dev/forums/-/message_boards/message/118328342
  - Ref - https://issues.liferay.com/browse/LPS-107983

- Need to place libthrift in deploy folder of liferay [Download URL](https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.13.0/libthrift-0.13.0.jar)

- For issue `Unresolved requirement: Require-Capability: osgi.ee; filter:="(osgi.ee=UNKNOWN)"` , added `-noee: true` in `bnd.bnd`
   - Ref - https://liferay.dev/forums/-/message_boards/message/113065360

```
jai@jai-VirtualBox:~$ java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode)

jai@jai-VirtualBox:~$ javac -version
javac 11.0.5

jai@jai-VirtualBox:~$ mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.5, vendor: Private Build, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-28-generic", arch: "amd64", family: "unix"

jai@jai-VirtualBox:~$ thrift -version
Thrift version 0.13.0

jai@jai-VirtualBox:~$ psql -V
psql (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

jai@jai-VirtualBox:~$ uname -a
Linux jai-VirtualBox 5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**CouchDb -2.1.2**
image

**SW360**
image

**Comment by JaideepPalit** [comment]
> Current liferay version liferay-ce-portal-7.2.1-ga2 is compatible till openjdk 11.0.5.
> -  Upgrading liferay version to 7.3.3 GA4 [download link](https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.3.3%20GA4/) which is compatible with higher version of openjdk 11.0.7
> - Need to enable Jquery and Font Awesome (For Glyphicons) as it is disabled by default.
>    - `Control Panel > Configuration > System Settings > Third Party > JQuery` - enable
>    - `Control Panel > Configuration > System Settings > Third Party > Font Awsome.` - enable
> - `Liferay 7.2.1 GA2` can be upgraded to `Liferay 7.3.3 GA4 `
>     1. Copy data folder from older version to newer version
>     2. Copy portal-ext.propertiies file from older version to newer version
>     3. Goto liferay -> tools - portal-tools-db-upgrade-client. update `app-server.properties` , `portal-upgrade-database.properties`, `portal-upgrade-ext.properties` accordingly
>         -  `app-server.properties` provide tomcat properties
>         -  `portal-upgrade-database.properties` provide postgres DB properties
>         -  `portal-upgrade-ext.properties` provide liferay.home path 
>     4. Execute `db_upgrade.sh`
> - For Clean setup of liferay 7.3.3 GA4 . Need to set `sw360.liferay.company.id=20098` in `/etc/sw360/sw360.properties`. 
>    - Reason - even if `company.default.web.id=sw360.org` is set in `portal-ext.properties` company id is getting evaluated to `20098` instead of expected value `20101`. So need to override in sw360.properties.

**Comment by mcjaeger** [comment]
tested with LF 721 looks still promising:
```
    default: [INFO] authorization-server ............................... SUCCESS [ 22.409 s]
    default: [INFO] resource-server .................................... SUCCESS [ 54.611 s]
    default: [INFO] ------------------------------------------------------------------------
    default: [INFO] BUILD SUCCESS
    default: [INFO] ------------------------------------------------------------------------
    default: [INFO] Total time:  08:57 min
    default: [INFO] Finished at: 2020-08-11T13:02:54Z
    default: [INFO] ------------------------------------------------------------------------
    default: - [shell-provisioning] End of frontend sw360 installation
    default: - [shell-provisioning] End of sw360 provisioning

==> default: Machine 'default' has a post `vagrant up` message. This is a message
==> default: from the creator of the Vagrantfile, and not from Vagrant itself:
==> default: 
==> default: End of provisioning. Please try to call sw360 using your browser, for example: https://localhost:8443/
blackmetal:sw360-single mcj$ vagrant ssh
Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)
...

siemagrant@ubuntu-bionic:~$ cd /sw360portal/
siemagrant@ubuntu-bionic:/sw360portal$ git status
On branch mcj/chore/java11
Your branch is up to date with 'origin/mcj/chore/java11'.
```

**Comment by mcjaeger** [comment]
hm, portal seem to work, except from the corners where search is needed because I have only a setup with couchdb 2.1 right now ...

**Comment by JaideepPalit** [comment]
Done rebase with master to include couchdb-lucene 2.1.0 changes

**Pull request merged**
