### PR TITLE
feat(ui-rest): Changes in Release information

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Changes in Release information  
>   - change title "Download URL" to "Source Code Download URL"
>   - add new data field "Binary Download URL"
>   - added null check in change log for merge release

> * Which issue is this pull request belonging to and how is it solving it? (*#964*)
> * Did you add or update any new dependencies that are required for your change? - No

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Review by smrutis1 — CHANGES_REQUESTED** [review]
**Few Remarks:**

* Please consider updating the field name from `downloadurl` to `sourceCodeDownloadurl`.
* Kindly add the documentation for new field `binaryDownloadUrl` in REST.

**Comment by JaideepPalit** [comment]
Thanks for review . Changes made

**Comment by mcjaeger** [comment]
(from discussion): moderation request coverage required

**Comment by JaideepPalit** [comment]
Fixed issue related to moderation request.

**Review by smrutis1 — APPROVED** [review]
Code looks good to me.

**Comment by smrutis1** [comment]
Tested successfully along with the scripts

**Pull request merged**
