### PR TITLE
fix(auth): fix screen name auth problem

### PR DESCRIPTION
**Pull request by blaumeiser-at-bosch**
This PR adds the possibility to use the rest auth server using the screen name (or ldap name) instead of the email address. This is necessary e.g. if someone configured SW360 to use the screen name as login.

To test that one could use an existing instance, change the login to "login via screen name"  and try to use rest-auth. Instead of the email address one then needs to pass the screen name in the request.

### CODE REVIEW

**Comment by maierthomas** [comment]
Test Result:

login with mail address
- oauth token: OK
- ui generated token: OK
-> test with resource server: OK

login with screen name:
**- oauth access token: NOK**
ui generated token: OK

Error Message:
`{
"error":"unauthorized",
"error_description":"No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken"
}`

**Comment by maxhbr** [comment]
# From Debugging:
## How do users authenticate: By Email Adress
```
$ curl -v --connect-timeout 2 --max-time 2 -u admin@sw360.org:t 'http://127.0.0.1:8080/api/jsonws/user/get-user-id-by-email-address?companyId=20155&emailAddress=admin@sw360.org'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'admin@sw360.org'
> GET /api/jsonws/user/get-user-id-by-email-address?companyId=20155&emailAddress=admin@sw360.org HTTP/1.1
> Host: 127.0.0.1:8080
> Authorization: Basic YWRtaW5Ac3czNjAub3JnOnQ=
> User-Agent: curl/7.62.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1
< Set-Cookie: JSESSIONID=2FC21823CABACDE972165A75B80305A8; Path=/; HttpOnly
< Set-Cookie: GUEST_LANGUAGE_ID=en_US; Expires=Sun, 13-Sep-2065 22:13:50 GMT; Path=/; HttpOnly
< Cache-Control: private, no-cache, no-store, must-revalidate
< Content-Type: application/json;charset=UTF-8
< Content-Length: 5
< Date: Wed, 30 Jan 2019 19:31:42 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
20821
```

```
$ curl -v --connect-timeout 2 --max-time 2 -u admin@sw360.org:t 'http://127.0.0.1:8080/api/jsonws/user/get-user-id-by-screen-name?companyId=20155&screenName=sw3607'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'admin@sw360.org'
> GET /api/jsonws/user/get-user-id-by-screen-name?companyId=20155&screenName=sw3607 HTTP/1.1
> Host: 127.0.0.1:8080
> Authorization: Basic YWRtaW5Ac3czNjAub3JnOnQ=
> User-Agent: curl/7.62.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1
< Set-Cookie: JSESSIONID=AC050D6A1BFA2BFF39CF93F2121D0D63; Path=/; HttpOnly
< Set-Cookie: GUEST_LANGUAGE_ID=en_US; Expires=Sun, 13-Sep-2065 22:13:50 GMT; Path=/; HttpOnly
< Cache-Control: private, no-cache, no-store, must-revalidate
< Content-Type: application/json;charset=UTF-8
< Content-Length: 5
< Date: Wed, 30 Jan 2019 19:31:42 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
20821
```
## How do users authenticate: By Screen Name

**Comment by maxhbr** [comment]
# The Problem:

The user ScreenName in the Liferay is case insensitive, but in SW360 we use the `externalId` of a user as the corresponding field and our search on this is case sensitive. So using the correct screen name with correct cases works.

One is even not able to look up the correct casing in liferay, since it is displayed in lowercase.

## Screenshots:

**Comment by maxhbr** [comment]
With the last commit b35b265 it should work now, even if the cases in the screenName do not match

(I have made external ID in our SW360 datamodel case insensitive)

**Pull request merged**
