### PR TITLE
feat(rest) Added route DELETE /releases/{ID},{ID2} to delete releases

### PR DESCRIPTION
**Pull request by blaumeiser-at-bosch**
Signed-off-by: Henrik Engelbrink <henrik.engelbrink@bosch-si.com>

### CODE REVIEW

**Comment by hengel2810** [comment]
This pull-request implements the functionality to delete multiple releases with one request and get a response which contains an error code for each release. The request response status code is always 207 (Multi-Status). It's only possible to delete releases which aren't linked to other resources.

Request: DELETE .../resource/api/releases/releaseId1,releaseId2

Response:
```
[
    {
        "resourceId":"releaseId1",
        "status":500
    },
    {
        "resourceId":"releaseId2",
        "status":200
    },
    {
        "resourceId":"releaseId3",
        "status":409
    }   
]
```

**Comment by maierthomas** [comment]
@hengel2810 please rebase your branch onto the current master! thank you

**Comment by alexbrdn** [comment]
Shouldn't wrong release id return 404 instead of 500?

**Comment by maierthomas** [comment]
Yes this would be the best solution to return 404 NOT_FOUND in this case.
Currently the REST API returns always 500 in this case because our thrift services throw a TException.

**Comment by hengel2810** [comment]
That's true, 404 would be a better error code for that. I'll fix that and rebase the branch afterwards.

**Comment by maierthomas** [comment]
@hengel2810 I would say 500 is okay in this case.
Because you have to change the thrift service implementation If you want to return 404.
You also should change the DELETE Batch method for component.
If you want we can write a small issue for this.

**Comment by hengel2810** [comment]
@maierthomas Ok, I've rebased the branch and it would be good to create an issue for the status code problem.

**Pull request merged**
