### PR TITLE
Update(Vulnerability): Improve the function of API to delete vulnerability information

### PR DESCRIPTION
**Pull request by hoangnt2**
Improve the function of API to delete vulnerability information

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Issue: #1606 

## Delete Vulnerability
- Delete vulnerability success:

   HTTP Status Code: 207
   Response body:

    [ {
　　　    "resourceId" : "external_id_1",
　　　     "status" : 200
    } ]

- Vulnerability is linked with other releases:

   HTTP Status Code: 207
   Response body:

    [ {
　　　    "resourceId" : "external_id_2",
　　　     "status" : 403
    } ]

- Vulnerability does not exists:

    HTTP Status Code: 207
    Response body:

    [ {
　　　    "resourceId" : "external_id_3",
　　　     "status" : 404
    } ]

## Delete Vulnerability Release Relationship:
- Delete relationship success:

   HTTP Status Code: 207
   Response body:

    [ {
　　　    "resourceId" : "external_id_1 - release_id_1",
　　　     "status" : 200
    } ]

- Relationship does not exist:

   HTTP Status Code: 207
   Response body:

    [ {
　　　    "resourceId" : "external_id_2 - release_id_2",
　　　     "status" : 404
    } ]

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Hi @hoangnt2, testing was successful.
Can you do same for Delete a release vulnerability relation API like you done for the above APIs.
Right now there is no response body for the mentioned API call.

**Comment by hoangnt2** [comment]
Hi @rudra-superrr, I can do same for Delete a release vulnerability relation API. 
But I need more information about response body to implement. Can you give me your suggestion? 
Or you can choose from 2 below options:
I look forward to hearing from you soon.

Option 1: Multiple Status Response
HTTP Status Code: 207
Response body:

[ {
　　　 "resourceId" : "vulnerability_external_id - release_id" , // separate id by '-' character 
　　　 "status" : 200
} ]

Option 2: Single Status
HTTP status code: 200

Response body:
{
    "vulnerabilityExternalId": "vulnerability_external_id",
    "releaseId": "release_id"
}

**Comment by rudra-superrr** [comment]
Hi @hoangnt2, second option looks good to me. 
Option 2: Single Status
HTTP status code: 200

Response body:
{
"vulnerabilityExternalId": "vulnerability_external_id",
"releaseId": "release_id"
}

**Comment by rudra-superrr** [comment]
Testing was successful. Thanks for adding the additional feature.

**Review by smrutis1 — APPROVED** [review]
Code looks good

**Pull request merged**
