### PR TITLE
fix(ecc): Script to cleanup ECC information in release

### PR DESCRIPTION
**Pull request by smrutis1**
Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

We found there are some releases having ECC information with duplicate key for the field (AL and ECCN) in lower cases . This script will get the releases having ecc information and verify if there is any duplicate key for al or eccn and will delete the duplicate one. This script also migrates the field case from upper case to lower case.

For example:
`"eccInformation" : {
"AL" : "N",
"ECCN" : "N",
"al" : "N",
"eccn" : "N",
"eccStatus" : "APPROVED"
}`

> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change? -  No

Issue: 

Please refer the description.

> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Getting the below 2 errors:
1. 2022-09-19 06:42:28.174 ERROR [http-nio-8080-exec-12][PortletServlet:119] null
javax.portlet.PortletException: org.apache.jasper.JasperException: javax.el.PropertyNotFoundException: The class 'org.eclipse.sw360.datahandler.thrift.components.EccInformation' does not have the property 'AL'.
2. Getting only eccStatus info through REST call:
    "eccInformation": {
                    "eccStatus": "APPROVED"
                },

**Comment by smrutis1** [comment]
> Getting the below 2 errors:
> 
> 1. 2022-09-19 06:42:28.174 ERROR [http-nio-8080-exec-12][PortletServlet:119] null
>    javax.portlet.PortletException: org.apache.jasper.JasperException: javax.el.PropertyNotFoundException: The class 'org.eclipse.sw360.datahandler.thrift.components.EccInformation' does not have the property 'AL'.

Fixed it.

> 2. Getting only eccStatus info through REST call:
>    "eccInformation": {
>    "eccStatus": "APPROVED"
>    },

Response is same with current main branch.

**Comment by rudra-superrr** [comment]
Testing was successful.

**Review by akapti — APPROVED** [review]
Code Looks good to me. 
Tested by @rudra-superrr

**Pull request merged**
