### PR TITLE
update(lang): add chinese lang property file

### PR DESCRIPTION
**Pull request by KoukiHama**
Signed-off-by: Kouki Hama <kouki1.hama@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue:  #1751 

I would like someone who understands Chinese to review this.
 
@shi9qiu translated and plan to make PR about Chinese lar files later by following to https://github.com/eclipse/sw360/blob/main/README_LANG.md

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by EttingerK** [comment]
A colleague of mine (Xiaoxiao) has reviewed the document with the following remarks: 
I just finished reviewing the document today, and I made some slight changes and recommendation, I attached the txt file to this email. I didn’t change the original text, the changes I made are all written after a hyphen “-”, after each phrase.
[Language_cn_r.txt](https://github.com/eclipse/sw360/files/10227073/Language_cn_r.txt)

**Comment by ag4ums** [comment]
language change in the from the user->account-settings, only changing the liferay specific fields, but not the custom sw360 text/fields, also its  need to be added in the home page frontend/sw360-portlet/src/main/resources/META-INF/resources/html/homepage/welcome/view.jsp,

**Comment by ag4ums** [comment]
@KoukiHama  may be we can make another issue/PR to completely adding the Chinese language, and merge this current one

**Comment by KoukiHama** [comment]
Ok. I will make new PR and issue soon after merge thia.

**Review by ag4ums — APPROVED** [review]
changes looks good working as expected

**Pull request merged**
