### PR TITLE
chores(upgrade): Upgrade Liferay to 7.4.3.18 GA18

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Upgrade Liferay to 7.4.3.18 GA18.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: 

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by KoukiHama** [comment]
@JaideepPalit  if you finish the this upgrade, could you mention to me? I would like to do test on my environment and give feedback to community.

**Comment by JaideepPalit** [comment]
Hi @KoukiHama  I think it is ready
You can give a test

**Comment by KoukiHama** [comment]
I was able to success to install.  GUI of liferay  was little changed.
After merge this pull request, I would like to update or add new page for  liferay setting like this.
https://github.com/eclipse/sw360/wiki/Deploy-Liferay7.3

**Comment by KoukiHama** [comment]
I think a few changes are needed for docker as well, but that should be done in other pull requests.

**Comment by heliocastro** [comment]
> I think a few changes are needed for docker as well, but that should be done in other pull requests.

I'm doing general test on docker now and comment here on review

**Comment by heliocastro** [comment]
sw360         | 18-May-2022 09:49:52.467 SEVERE [main] org.apache.catalina.startup.ContextConfig.processContextConfig Parse error in context.xml for []
sw360         |         org.xml.sax.SAXParseException; systemId: file:/app/sw360/tomcat-9.0.56/conf/Catalina/localhost/ROOT.xml; lineNumber: 2; columnNumber: 79; Error at line [2] column [79]: [com.liferay.support.tomcat.util.scan.NOPJarScanner]

**Comment by KoukiHama** [comment]
https://github.com/eclipse/sw360#readme
should be updated too.

**Comment by heliocastro** [comment]
> Any idea ? This is from docker build
> 
> ```
> sw360         | 18-May-2022 09:49:52.467 SEVERE [main] org.apache.catalina.startup.ContextConfig.processContextConfig Parse error in context.xml for []
> sw360         |         org.xml.sax.SAXParseException; systemId: file:/app/sw360/tomcat-9.0.56/conf/Catalina/localhost/ROOT.xml; lineNumber: 2; columnNumber: 79; Error at line [2] column [79]: [com.liferay.support.tomcat.util.scan.NOPJarScanner]
> ```

It happens when you try to keep original database. Clean start work.
Please do check migration, aside that  is good to go

**Review by heliocastro — CHANGES_REQUESTED** [review]
Is not working properly.
Trying to create an user:
`2022-05-19 13:07:20.747 ERROR [http-nio-8080-exec-4][UserPortlet:418] Error creating organizations test
com.liferay.portal.kernel.exception.NoSuchCountryException: No Country exists with the primary key 19
at com.liferay.portal.service.persistence.impl.CountryPersistenceImpl.findByPrimaryKey(CountryPersistenceImpl.java:5229) ~[portal-impl.jar:?]
at com.liferay.portal.service.persistence.impl.CountryPersistenceImpl.findByPrimaryKey(CountryPersistenceImpl.java:5247) ~[portal-impl.jar:?]
at com.liferay.portal.service.impl.OrganizationLocalServiceImpl.validate(OrganizationLocalServiceImpl.java:2549) ~[portal-impl.jar:?]
at com.liferay.portal.service.impl.OrganizationLocalServiceImpl.validate(OrganizationLocalServiceImpl.java:2561) ~[portal-impl.jar:?]
at com.liferay.portal.service.impl.OrganizationLocalServiceImpl.addOrganization(OrganizationLocalServiceImpl.java:272) ~[portal-impl.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60) ~[portal-impl.jar:?]
at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
at com.sun.proxy.$Proxy105.addOrganization(Unknown Source) ~[?:?]
at com.liferay.portal.service.impl.OrganizationServiceImpl.addOrganization(OrganizationServiceImpl.java:206) ~[portal-impl.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]`

**Comment by smrutis1** [comment]
@heliocastro Thanks for having a look. I have tested it in my instance(normal setup, not docker), it's working for me.

Could you please mention the exact steps to reproduce, if possible. Or else could you please verify the migration steps mentioned in the comment section of the PR https://github.com/eclipse/sw360/pull/916#issuecomment-667818520

**Comment by heliocastro** [comment]
Can you try with this PR ?
[#22272E](https://github.com/eclipse/sw360/pull/1531)
Is docker update on top of this one.

The issue exists on clean installs, so something extra now is needed to add in config/bootstraping.

**Comment by heliocastro** [comment]
Issue: Try to create a user assigned to unknown organization
Process: sw360 try to create an department/organization with invalid country id, so invalidating user creation at all
So far, after create some org, user can be created and for now regular operation can be done.

There's a secon bug which freeze the web interface after user creation, and force an reload

**Comment by rudra-superrr** [comment]
Issues:
1. Not able to link Projects and Releases with the existing Projects.
2. Also not able to link Releases with the Releases in the Component section.
3. Not displaying License Clearing info in proper Tabular format in Project Section.
4. Not able to add License Info To Release in Project Section when there is already a Release linked to that Project.

LinkProject

LinkRelease

LinkReleaseComponent

LicenseClearingInfo

NoLinkedReleases

.

**Comment by smrutis1** [comment]
@rudra-superrr & @heliocastro Thanks for giving a test. The mentioned issues with respect to UI and county id has been fixed.

**Comment by akapti** [comment]
found couple of issues while testing:

- Attachment upload UI is not aligned and border is missing:
image
- `User` portlet under `Admin` portlet is hanged after importing the users into `SW360` using `CSV` file.

**Comment by smrutis1** [comment]
@akapti The mentioned issues has been fixed. Please verify when get a chance.

**Comment by akapti** [comment]
> @akapti The mentioned issues has been fixed. Please verify when get a chance.

One minor issue is with the session messages being displayed. 
Maybe we can ignore this for now and create another issue and fix it once this PR gets merged.

Currently in Liferay 7.4.3 the session messages are being displayed as below:
image


Session message in Liferay 7.3.3:
image

**Comment by heliocastro** [comment]
There's another layout issues. This is sign-in really first issue:

image

**Comment by smrutis1** [comment]
(from discussion):
It is decided to fix the issue as part of another created issue. (Issue Reference:- https://github.com/eclipse/sw360/issues/1614)

**Pull request merged**
