### PR TITLE
Cleanup dependencies for backend services

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Issue: None - cleanup

This PR aims to simplify the dependency tree for the backend. To obtain a less memory-intensive setup it would be great to package all backend-services together. This requires only one set of dependencies for all backend services to work reliably.

While trying to solve issues with different versions of dependencies, I also noticed that some of the dependencies are used in several places but not referenced from the dependencyManagement section of the parent pom, while others are. This PR therefore:

- aims to put all (backend) dependencies to the parent pom's dependencyManagement
- if two dependencies have different versions, tries to upgrade the dependencies
- also increases dependency versions for several minor dependencies
- update spdx tools dependency to the latest possible version
- update dependencies so that their natural transitive dependencies match the dependency versions used by sw360 whenever possible to avoid failures in transitive dependencies

## Testing

Note that moving versions to `dependencyManagement` may suddenly change the version of transitive dependencies due to the fact how Maven resolves dependencies. I tried to ensure that those dependencies still work well together and found no explicit problems - `mvn clean install` for instance runs cleanly.

### CODE REVIEW

**Comment by mcjaeger** [comment]
I deployed the branch two times now, but I get an errors like: 
```
2020-10-28 08:25:35.758 ERROR [Framework Event Dispatcher: Equinox Container: 83f00010-cb36-4d14-b7de-b0526457e6c4][Framework:93] FrameworkEvent ERROR 
org.osgi.framework.BundleException: Could not resolve module: sw360-datahandler [1183]_  Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.11.0,3.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```
or
```
org.osgi.framework.BundleException: Could not resolve module: sw360-common-io [1182]_  Unresolved requirement: Import-Package: org.eclipse.sw360.datahandler.common; version="[1.0.0,2.0.0)"_    -> Export-Package: org.eclipse.sw360.datahandler.common; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.fasterxml.jackson.databind.node,com.google.common.base,com.google.common.collect,org.apache.commons.csv,org.apache.logging.log4j,org.apache.thrift,org.apache.thrift.meta_data,org.eclipse.sw360.datahandler.thrift,org.eclipse.sw360.datahandler.thrift.attachments,org.eclipse.sw360.datahandler.thrift.components,org.eclipse.sw360.datahandler.thrift.licenses,org.eclipse.sw360.datahandler.thrift.moderation,org.eclipse.sw360.datahandler.thrift.projects,org.eclipse.sw360.datahandler.thrift.users,org.eclipse.sw360.datahandler.thrift.vulnerabilities,org.ektorp,org.ektorp.http"_       sw360-datahandler [1183]_         Unresolved requirement: Import-Package: com.fasterxml.jackson.annotation; version="[2.11.0,3.0.0)"_  Unresolved requirement: Import-Package: org.apache.thrift; version="[0.13.0,1.0.0)"_    -> Export-Package: org.apache.thrift; bundle-symbolic-name="sw360-datahandler"; bundle-version="1.0.0"; version="0.13.0"; uses:="org.apache.thrift.async,org.apache.thrift.protocol,org.apache.thrift.server,org.apache.thrift.transport,org.slf4j"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1297)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1270)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1259)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:519)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:369)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:320)
```
at deployment. I am not sure about the root cause though ...

**Comment by mcjaeger** [comment]
(did a maven clean install before as well)

**Comment by Martin-Idel-SI** [comment]
I'm looking into it.

**Comment by Martin-Idel-SI** [comment]
@mcjaeger The problem is that the deployments manage some dependencies separately - in other words there is a duplication of dependency information. I'll try to resolve this with the sw360chores repository and post a PR to sw360vagrant since this is managed similarly.

**Comment by Martin-Idel-SI** [comment]
@mcjaeger So the problem seems to be the separate dependency handling in vagrant/chores. 

Due to process limitations it'll take some time for me to access sw360vagrant. Here is a patch for sw360vagrant that should allow you to build the project again without errors - at least a similar patch works for me for sw360chores which we'll contribute shortly:

``` 
diff --git a/download-packages.sh b/download-packages.sh
index 4cbc675..b45192f 100755
--- a/download-packages.sh
+++ b/download-packages.sh
@@ -25,16 +25,16 @@
 packages='https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-vagrant.box
 https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.3.3%20GA4/liferay-ce-portal-tomcat-7.3.3-ga4-20200701015330959.tar.gz
 https://search.maven.org/remotecontent?filepath=commons-codec/commons-codec/1.12/commons-codec-1.12.jar commons-codec-1.12.jar
-https://search.maven.org/remotecontent?filepath=org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar commons-collections4-4.1.jar
+https://search.maven.org/remotecontent?filepath=org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar commons-collections4-4.4.jar
 https://search.maven.org/remotecontent?filepath=org/apache/commons/commons-csv/1.4/commons-csv-1.4.jar commons-csv-1.4.jar
 https://search.maven.org/remotecontent?filepath=commons-io/commons-io/2.6/commons-io-2.6.jar commons-io-2.6.jar
 https://search.maven.org/remotecontent?filepath=commons-lang/commons-lang/2.4/commons-lang-2.4.jar commons-lang-2.4.jar
 https://search.maven.org/remotecontent?filepath=commons-logging/commons-logging/1.2/commons-logging-1.2.jar commons-logging-1.2.jar
 https://search.maven.org/remotecontent?filepath=com/google/code/gson/gson/2.8.5/gson-2.8.5.jar gson-2.8.5.jar
 https://search.maven.org/remotecontent?filepath=com/google/guava/guava/21.0/guava-21.0.jar guava-21.0.jar
-https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-annotations/2.9.8/jackson-annotations-2.9.8.jar jackson-annotations-2.9.8.jar
-https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar jackson-core-2.9.8.jar
-https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-databind/2.9.8/jackson-databind-2.9.8.jar jackson-databind-2.9.8.jar
+https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-annotations/2.11.3/jackson-annotations-2.11.3.jar jackson-annotations-2.11.3.jar
+https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-core/2.11.3/jackson-core-2.11.3.jar jackson-core-2.11.3.jar
+https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/core/jackson-databind/2.11.3/jackson-databind-2.11.3.jar jackson-databind-2.11.3.jar
 https://jdbc.postgresql.org/download/postgresql-42.2.9.jar postgresql-42.2.9.jar
 https://dist.apache.org/repos/dist/release/thrift/0.13.0/thrift-0.13.0.tar.gz
 https://github.com/rnewson/couchdb-lucene/archive/v2.1.0.tar.gz ./couchdb-lucene.tar.gz
``` 
This updates all dependencies I updated in sw360. Since the OSGi bundling requires those dependencies to be present but doesn't bundle them with the sw360datahandler, they are separately managed in the vagrant/chores project (which is very awkward to be honest).

**Comment by mcjaeger** [comment]
sw360 works normally with the proposed changes, however we should update the vagrant before that otherwise the master will not build with the reference deployment.

**Review by mcjaeger — APPROVED** [review]
changes make much sense to streamline dependencies

**Comment by mcjaeger** [comment]
I would like to make sure that with such dep changes on many areas, we should have a in depth check of the sw360 functionality ...

**Pull request merged**
