### PR TITLE
test: add script to start temporary couchdb with docker

### PR DESCRIPTION
**Pull request by maxhbr**
This is a super simple PR which just adds a simple script which is useful for lightweight testing

### CODE REVIEW

**Comment by mcjaeger** [comment]
is this also conventional cc? `test:`

**Comment by lepokle** [comment]
It works like expected. Maybe two little improvements:
- start log messages with an uppercase
- Log after start or shutdown operation that it is finished, like "Container is now up and running." (I was a little bit unsure it it really is)

Can be merged afterwards.

**Comment by maxhbr** [comment]
> is this also conventional cc? `test:`

Yes, the scope is optional.

**Comment by lepokle** [comment]
In addition I'm not able to successfully run the test in this test instance:
```
org.ektorp.DbAccessException: com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors
 at [Source: org.ektorp.http.StdHttpResponse$ConnectionReleasingInputStream@77429040; line: 1, column: 31]
	at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
	at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:128)
	at org.ektorp.http.RestTemplate.postUncached(RestTemplate.java:89)
	at org.ektorp.impl.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:49)
	at org.ektorp.impl.StdCouchDbConnector.executeQuery(StdCouchDbConnector.java:433)
	at org.ektorp.impl.StdCouchDbConnector.queryView(StdCouchDbConnector.java:429)
	at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.get(DatabaseConnector.java:159)
	at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.get(DatabaseConnector.java:163)
	at org.eclipse.sw360.datahandler.couchdb.DatabaseRepository.get(DatabaseRepository.java:210)
	at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.getProjectsById(ProjectDatabaseHandler.java:462)
	at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.preloadLinkedProjects(ProjectDatabaseHandler.java:338)
	at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.getLinkedProjects(ProjectDatabaseHandler.java:318)
	at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest.testGetLinkedProjectsOfProject(ProjectDatabaseHandlerTest.java:368)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors
 at [Source: org.ektorp.http.StdHttpResponse$ConnectionReleasingInputStream@77429040; line: 1, column: 31]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:799)
	at com.fasterxml.jackson.core.base.ParserBase.getLongValue(ParserBase.java:670)
	at org.ektorp.impl.QueryResultParser.parseResult(QueryResultParser.java:75)
	at org.ektorp.impl.QueryResultParser.parseResult(QueryResultParser.java:59)
	at org.ektorp.impl.EmbeddedDocViewResponseHandler.success(EmbeddedDocViewResponseHandler.java:37)
	at org.ektorp.impl.EmbeddedDocViewResponseHandler.success(EmbeddedDocViewResponseHandler.java:16)
	at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:126)
	... 44 more

```

**Comment by kallesoranko** [comment]
I tried to test this PR and I ran the script and container did start, but when I ran `mvn install`, there seems to be failure in the tests themselves. Here is the log:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/ProjectExporterTest.java:[42,36] cannot access ComponentService.Iface
  class file for ComponentService.Iface not found
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java:[192,36] incompatible types: java.util.List<org.eclipse.sw360.datahandler.thrift.licenses.Todo> cannot be converted to java.util.List<Todo>
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java:[202,40] incompatible types: java.util.List<Todo> cannot be converted to java.util.List<org.eclipse.sw360.datahandler.thrift.licenses.Todo>
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java:[208,40] incompatible types: java.util.List<Todo> cannot be converted to java.util.List<org.eclipse.sw360.datahandler.thrift.licenses.Todo>
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] sw360 .............................................. SUCCESS [  4.116 s]
[INFO] build-configuration ................................ SUCCESS [  3.587 s]
[INFO] libraries .......................................... SUCCESS [  2.748 s]
[INFO] lib-datahandler .................................... SUCCESS [02:44 min]
[INFO] commonIO ........................................... SUCCESS [  1.689 s]
[INFO] exporters .......................................... FAILURE [  1.087 s]
[INFO] importers .......................................... SKIPPED
[INFO] license-importer ................................... SKIPPED
[INFO] backend ............................................ SKIPPED
[INFO] src-common ......................................... SKIPPED
[INFO] backend-src ........................................ SKIPPED
[INFO] src-attachments .................................... SKIPPED
[INFO] src-components ..................................... SKIPPED
[INFO] src-vendors ........................................ SKIPPED
[INFO] component-importer ................................. SKIPPED
[INFO] src-licenses ....................................... SKIPPED
[INFO] src-users .......................................... SKIPPED
[INFO] src-search ......................................... SKIPPED
[INFO] src-projects ....................................... SKIPPED
[INFO] src-moderation ..................................... SKIPPED
[INFO] src-fossology ...................................... SKIPPED
[INFO] src-vulnerabilities ................................ SKIPPED
[INFO] src-licenseinfo .................................... SKIPPED
[INFO] src-cvesearch ...................................... SKIPPED
[INFO] src-schedule ....................................... SKIPPED
[INFO] src-wsimport ....................................... SKIPPED
[INFO] svc-common ......................................... SKIPPED
[INFO] backend-svc ........................................ SKIPPED
[INFO] svc-licenses ....................................... SKIPPED
[INFO] svc-users .......................................... SKIPPED
[INFO] svc-vendors ........................................ SKIPPED
[INFO] svc-search ......................................... SKIPPED
[INFO] svc-components ..................................... SKIPPED
[INFO] svc-projects ....................................... SKIPPED
[INFO] svc-attachments .................................... SKIPPED
[INFO] svc-moderation ..................................... SKIPPED
[INFO] svc-fossology ...................................... SKIPPED
[INFO] svc-vulnerabilities ................................ SKIPPED
[INFO] svc-cvesearch ...................................... SKIPPED
[INFO] svc-licenseinfo .................................... SKIPPED
[INFO] svc-schedule ....................................... SKIPPED
[INFO] svc-wsimport ....................................... SKIPPED
[INFO] backend-utils ...................................... SKIPPED
[INFO] frontend ........................................... SKIPPED
[INFO] SW360 Layout Template .............................. SKIPPED
[INFO] sw360-portlet ...................................... SKIPPED
[INFO] sw360-theme Theme .................................. SKIPPED
[INFO] rest ............................................... SKIPPED
[INFO] rest-common ........................................ SKIPPED
[INFO] authorization-server ............................... SKIPPED
[INFO] resource-server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:59 min
[INFO] Finished at: 2019-07-17T15:41:03+03:00
[INFO] Final Memory: 68M/1395M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project exporters: Compilation failure: Compilation failure:
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/ProjectExporterTest.java:[42,36] cannot access ComponentService.Iface
[ERROR]   class file for ComponentService.Iface not found
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java:[192,36] incompatible types: java.util.List<org.eclipse.sw360.datahandler.thrift.licenses.Todo> cannot be converted to java.util.List<Todo>
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java:[202,40] incompatible types: java.util.List<Todo> cannot be converted to java.util.List<org.eclipse.sw360.datahandler.thrift.licenses.Todo>
[ERROR] /C:/Users/kalle/kallesoranko/sw360/libraries/exporters/src/test/java/org/eclipse/sw360/exporter/utils/ConvertRecordTest.java:[208,40] incompatible types: java.util.List<Todo> cannot be converted to java.util.List<org.eclipse.sw360.datahandler.thrift.licenses.Todo>
```

**Comment by maxhbr** [comment]
can you call `mvn install` on master? since my PR might be out of sync

**Comment by kallesoranko** [comment]
sorry, this was on master and I also tested it on older branch and there was same error

**Comment by lepokle** [comment]
@kallesoranko This should have todo nothing with the PR.
Does any other branch work, e.g. `mvn clean package`?

**Comment by kallesoranko** [comment]
Calling `mvn clean` helped to get rid of that compilation error but now I get same test failure as @lepokle.

Here is the log:

```
testSanityCheckSucceeds(org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest)  Time elapsed: 1.049 sec  <<< ERROR!
org.ektorp.DbAccessException: com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors
 at [Source: org.ektorp.http.StdHttpResponse$ConnectionReleasingInputStream@13213f26; line: 1, column: 30]
        at org.ektorp.util.Exceptions.propagate(Exceptions.java:19)
        at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:128)
        at org.ektorp.http.RestTemplate.postUncached(RestTemplate.java:89)
        at org.ektorp.impl.DefaultQueryExecutor.executeQuery(DefaultQueryExecutor.java:49)
        at org.ektorp.impl.StdCouchDbConnector.executeQuery(StdCouchDbConnector.java:433)
        at org.ektorp.impl.StdCouchDbConnector.queryView(StdCouchDbConnector.java:429)
        at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.get(DatabaseConnector.java:159)
        at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.get(DatabaseConnector.java:163)
        at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.deleteIds(DatabaseConnector.java:253)
        at org.eclipse.sw360.datahandler.couchdb.AttachmentConnector.deleteAttachmentsByIds(AttachmentConnector.java:86)
        at org.eclipse.sw360.datahandler.couchdb.AttachmentConnector.deleteAttachmentDifference(AttachmentConnector.java:101)
        at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.updateProject(ProjectDatabaseHandler.java:208)
        at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest.testSanityCheckSucceeds(ProjectDatabaseHandlerTest.java:327)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
        at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors
 at [Source: org.ektorp.http.StdHttpResponse$ConnectionReleasingInputStream@13213f26; line: 1, column: 30]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
        at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:799)
        at com.fasterxml.jackson.core.base.ParserBase.getLongValue(ParserBase.java:670)
        at org.ektorp.impl.QueryResultParser.parseResult(QueryResultParser.java:75)
        at org.ektorp.impl.QueryResultParser.parseResult(QueryResultParser.java:59)
        at org.ektorp.impl.EmbeddedDocViewResponseHandler.success(EmbeddedDocViewResponseHandler.java:37)
        at org.ektorp.impl.EmbeddedDocViewResponseHandler.success(EmbeddedDocViewResponseHandler.java:16)
        at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:126)
        ... 44 more

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

Results :

Tests in error:
  testGetLinkedProjectsOfProject(org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest): com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors(..)
  testReleaseIdToProjects(org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest): com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors(..)
  testUpdateProject2_1(org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest): com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors(..)
  testGetLinkedProjectsOfProjectForClonedProject(org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest): com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors(..)
  testSanityCheckSucceeds(org.eclipse.sw360.datahandler.db.ProjectDatabaseHandlerTest): com.fasterxml.jackson.core.JsonParseException: Current token (VALUE_NULL) not numeric, can not use numeric value accessors(..)

Tests run: 20, Failures: 0, Errors: 5, Skipped: 0
```

**Comment by maxhbr** [comment]
I have rebased and retested. I still can not reproduce the errors.

**Comment by kallesoranko** [comment]
Re-tested this PR, this time with both Windows and Ubuntu desktop, but unfortunately with same outcome:
``` bash
Results :

Tests in error: 
  ProjectDatabaseHandlerTest.testGetLinkedProjectsOfProject:368 » DbAccess com.f...
  ProjectDatabaseHandlerTest.testReleaseIdToProjects:347 » DbAccess com.fasterxm...
  ProjectDatabaseHandlerTest.testUpdateProject2_1:142 » DbAccess com.fasterxml.j...
  ProjectDatabaseHandlerTest.testGetLinkedProjectsOfProjectForClonedProject:381 » DbAccess
  ProjectDatabaseHandlerTest.testSanityCheckSucceeds:327 » DbAccess com.fasterxm...

Tests run: 20, Failures: 0, Errors: 5, Skipped: 0
```

**Comment by maxhbr** [comment]
@blaumeiser-at-bosch This PR can be fixed by the following minor change:
```diff
diff --git a/scripts/startCouchdbForTests.sh b/scripts/startCouchdbForTests.sh
index d4765c4..9ec56b7 100755
--- a/scripts/startCouchdbForTests.sh
+++ b/scripts/startCouchdbForTests.sh
@@ -25,7 +25,7 @@ if [[ ! "$(docker ps -q -f name=$NAME)" ]]; then
            -p 5984:5984 \
            -d \
            --name "$NAME" \
-           couchdb
+           couchdb:1
     echo "Test container is started and listening on 5984."
 else
     echo "Test container is running, shutting it down ..."
```

**Comment by kallesoranko** [comment]
Tested successfully with the proposed changed from @maxhbr  👍

**Comment by mcjaeger** [comment]
(from discussion): there needs to be the change "with the colon"  in this PR

```
diff --git a/scripts/startCouchdbForTests.sh b/scripts/startCouchdbForTests.sh
index d4765c4..9ec56b7 100755
--- a/scripts/startCouchdbForTests.sh
+++ b/scripts/startCouchdbForTests.sh
@@ -25,7 +25,7 @@ if [[ ! "$(docker ps -q -f name=$NAME)" ]]; then
            -p 5984:5984 \
            -d \
            --name "$NAME" \
-           couchdb
+           couchdb:1
```

needs to be done by someone with write rights in this branch

**Pull request merged**
