### PR TITLE
feat(tabview): added better navigation support for tabview 

### LINKED ISSUE #373: Going back and forth with browser buttons misses last viewed detail view section
When navigating detail views and going forward and backwards between data sets, then the detail view jumps always back at the first detail view pane(mostly summary), which is annoying. It should remember the actual detail view shown.

Example: When jumping to a release data set from a project listing of releases by clicking the link, then going back to the project data set using the browser buttons, then, the summary (first) detail view is shown. Then, the user needs to do an additional click to jump to the actual last visited view.

### PR DESCRIPTION
**Pull request by imaykay**
Basic information in commit message of 9fb2863

Since we use tabviews on most pages, I guess most of the application needs testing.

closes #373

### CODE REVIEW

**Comment by maxhbr** [comment]
Note: we usually rebase to update branches

**Comment by maierthomas** [comment]
<in testing>

**Comment by imaykay** [comment]
@maierthomas I sadly cannot reproduce the behaviour in firefox. I see the anchors and the tab changes via back/forward are working fine. I am using Firefox 64.0.2. on Mac OS. Any hint what might be the issue on your side?

**Comment by imaykay** [comment]
@maierthomas regarding your findings:
1. As I said, FF just works for me. Maybe someone else can test this branch in FF as well or you could give further input.
2. Vulnerabilities tab is fixed. There was a typo in the div's id even before my change.
3. On my machine I do not see much difference to the page/tab building before. So I would suggest to add a spinner in a separate issue.
4. Will be fixed in the named issue.

**Comment by smrutis1** [comment]
Have tested this pull request and below are the steps followed and findings.

**Test Steps followed** :
1. Clicked on "Project" tab.
2. Selected any Project under "Project Name".
3. Clicked "Linked Releases And Project"
4. Selected anyone under "Name" (Switches to Component tab)
5. Selected Attachment.

**Findings:** 
1. For backward navigation, toggling all the browsed pages/links as expected. 
2. For forward navigation, getting stuck in 'Summary' under 'Component' tab, not moving to Attachment.

**Comment by imaykay** [comment]
I just resolved the merge conflicts.

@smrutis1 do you have more input on the forward navigation issue? For me in Chrome on Mac OS the forward navigation also just works.

**Comment by smrutis1** [comment]
@imaykay  this seems to be a browser specific issue. In chrome, it is working as expected, but in firefox(tested on windows and Ubuntu OS), the issue seems to be there.

**Comment by maxhbr** [comment]
@imaykay is this PR **WIP**

**Pull request merged**
