### PR TITLE
fix(ui): datepicker date and year selection is made available

### PR DESCRIPTION
**Pull request by aratib**
Month and year selection is made available in datepicker.

### CODE REVIEW

**Comment by maierthomas** [comment]
thank you aratib for this contribution.
Please use sign-off commits by using "commit -s".

**Comment by maxhbr** [comment]
Please fix the history:

**Comment by maierthomas** [comment]
@aratib can you please fix the merge conflicts and squash your commits into one?

**Comment by aratib** [comment]
Done

**Comment by maxhbr** [comment]
@aratib you have committed an unresolved conflict, please fix this:

**Comment by maierthomas** [comment]
tested successfully

image

**Comment by maxhbr** [comment]
Please fix the commit message:

Also the signoff has to be in the last line and with the full name

**Pull request merged**
