### PR TITLE
feat(AddProjectReleaseRelation): add a project release relation for source code snippets

### PR DESCRIPTION
**Pull request by JaideepPalit**
Added new project release relation `Code Snippet` for source code snippets

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by smrutis1** [comment]
Tested the PR. May be It would be good to add the description in the tool tip for code snippet. 

releaserelation

**Comment by mcjaeger** [comment]
@smrutis1 I agree, but we have a number of other open / missing content on mouse over as well...

**Comment by mcjaeger** [comment]
@JaideepPalit how about adding "From references release, a fragment is used."

**Comment by JaideepPalit** [comment]
Thanks @mcjaeger . I have added the description in the tooltip.

**Pull request merged**
