### PR TITLE
feat(ui):Rename and Re-arrange the Tabs under Projects section

### PR DESCRIPTION
**Pull request by ravi110336**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

>  Renamed and re-arranged the projects tab.
> * Which issue is this pull request belonging to and how is it solving it? (#1108 )
> * Did you add or update any new dependencies that are required for your change? No

   - Open sw360, click on the Projects tab and open a project and validate the different tabs under project section.
> Have you implemented any additional tests? No

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Ravindra Kumar kumar.ravindra@siemens.com

### CODE REVIEW

**Comment by ravi110336** [comment]
Added the Signed off by, and re validated.

**Comment by mcjaeger** [comment]
please consider also changing the language files:

https://github.com/eclipse/sw360/blob/135ada4deb1ec576428d900394b3bb295669b204/frontend/sw360-portlet/src/main/resources/content/Language_ja.properties#L387

https://github.com/eclipse/sw360/blob/135ada4deb1ec576428d900394b3bb295669b204/frontend/sw360-portlet/src/main/resources/content/Language_vi.properties#L388

**Comment by ravi110336** [comment]
As per review comments, Reverted the code changes for Export Control and renamed as ECC, Added the changes in all language properties file.

**Comment by smrutis1** [comment]
@ravi110336 , Kindly consider to squash the commits.

**Comment by ravi110336** [comment]
@smrutis1 ,Squashed the commits, Please check and let me know if any issue.

**Review by smrutis1 — APPROVED** [review]
Code looks good. Tested successfully.

**Pull request merged**
