### PR TITLE
feat(Obligation): Add License Obligation from License Database based on licenses found in accepted attachments in Release and its LicenseInfo attachmentUsage in Project

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Add License Obligation from License Database based on licenses found in accepted attachments in Release and its LicenseInfo attachmentUsage in Project
> * Which issue is this pull request belonging to and how is it solving it? (*#1046*)
> * Did you add or update any new dependencies that are required for your change?

Capture

image

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by JaideepPalit** [comment]
Resolved merge conflict

**Comment by JaideepPalit** [comment]
Fixed code formatting.

**Comment by mcjaeger** [comment]
unfortunately, not tested successful - obligations do not get added. After adding, list remains empty. Can try to add multiple times, but addition is not persisted

what I did:

1. empty instance
2. import spdx licenses from admin, licenses
3. add bogus obligations for zlib and apache-2.0
4. create some component and releases using the following two SPDX example files as component license information attachment:
[two spdx example files.zip](https://github.com/eclipse/sw360/files/5575413/two.spdx.example.files.zip)
5. approve the attachments (otherwise they are not considered for attachments
6. add the releases to a project just created
7. add attachment usage for these attachments
8. go to obligations and click add obligation from license database
-> bogus obligations appear and can be selected
Screenshot 2020-11-20 at 19 33 45
Screenshot 2020-11-20 at 19 33 52

9. add all obligations, or some, does not make a difference, maybe apply some status and comment, does not make a difference:
Screenshot 2020-11-20 at 19 34 14

10. empty obligations is the result:

Screenshot 2020-11-20 at 19 34 23

11. change log items are created, one of them apparently empty but add obligations is not possible.
12. log when adding obligations:
```
2020-11-20 18:14:49 INFO  PortletUtils:232 - No ids transmitted. All attachments will be deleted.
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:410 - Generating ChangeLogs.
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:342 - Initialize ChangeLogs for Document Id : f1805cf57788c46c4774e0571005d1d8
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:598 - Record Changes For Existing Doc.
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:638 - Initialize ChangeLogs for Attachments.
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:410 - Generating ChangeLogs.
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:342 - Initialize ChangeLogs for Document Id : 082cb2f79954119d5a177565d40031fb
2020-11-20 18:14:49 INFO  DatabaseHandlerUtil:598 - Record Changes For Existing Doc.
```

Screenshot 2020-11-20 at 19 24 33
Screenshot 2020-11-20 at 19 23 55

**Comment by mcjaeger** [comment]
tested with a clean vagrant build (download packages, generate box, vagrant up, new setup of sw360) (also testing the vagrant PR)

same error. you can add a simple obligation just created:

Screenshot 2020-11-22 at 22 41 13

the summary looks like this:

Screenshot 2020-11-22 at 22 41 18

but updating the project does not save it:

Screenshot 2020-11-22 at 22 41 03

entire log items (started with cleared terminal) for the steps described above:

```
2020-11-22 21:41:00 INFO  PortletUtils:232 - No ids transmitted. All attachments will be deleted.
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:410 - Generating ChangeLogs.
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:342 - Initialize ChangeLogs for Document Id : 425a472310132aff69866831b100600c
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:598 - Record Changes For Existing Doc.
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:638 - Initialize ChangeLogs for Attachments.
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:410 - Generating ChangeLogs.
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:342 - Initialize ChangeLogs for Document Id : 425a472310132aff69866831b1007868
2020-11-22 21:41:00 INFO  DatabaseHandlerUtil:598 - Record Changes For Existing Doc.
```

**Comment by JaideepPalit** [comment]
Thanks for the test. Fixed the above issue.

**Comment by smrutis1** [comment]
@mcjaeger @JaideepPalit , Followed the mentioned steps, Seems to work now. Snapshots for reference.

image

image

image

image

**Review by smrutis1 — APPROVED** [review]
Code looks Ok. Tested successfully.

**Pull request merged**
