### PR TITLE
feat(ui): Add function to create new License Type and link it to License

### PR DESCRIPTION
**Pull request by quan-tv**
Signed-off-by: Tran Vu Quan <quan1.tranvu@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> - Implement Admin License Type management function
> - Allow user to select License Type when add/edit License

Issue: #936 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by KoukiHama** [comment]
@quan-tv 
This commit message is not follow this.
https://github.com/eclipse/sw360/wiki/Dev-Semantic-Commits#example-of-semantic-commit-message

#1267 #1266 #1265 have same issue.

**Comment by quan-tv** [comment]
> @quan-tv
> This commit message does not follow this.
> https://github.com/eclipse/sw360/wiki/Dev-Semantic-Commits#example-of-semantic-commit-message
> 
> Please fix them.
> 
> #1267 #1266 #1265 have same issue.

I have updated commit message for all 4 pull requests.

**Comment by ravi110336** [comment]
Hi @quan-tv , I was testing the PR but I am not seeing the License Types in the Admin Dropdown. I get the error message, when tried to open the License Types from the Admin Page. Could you please check and let me know if I am missing anything.

**Screenshot:**
image

**Comment by quan-tv** [comment]
> Hi @quan-tv , I was testing the PR but I am not seeing the License Types in the Admin Dropdown. I get the error message, when tried to open the License Types from the Admin Page. Could you please check and let me know if I am missing anything.
> 
> **Screenshot:**
> image

Hi @ravi110336,

It is required to re-import the lar file. Could you please import and try again?

# I also updated the PR comment with this information.

**Comment by ravi110336** [comment]
@quan-tv , Thanks for the info. I have re-imported the lar file and License Type is coming properly.
I have reviewed and tested the below scenario and looks good.

I have one question though: when we create a license type list the **licensetypeId** in database, is a negative value for the white and yellow license, is there is any significance for negative values. 
image


**License Type in admin page:**
image
 
**Add License Type List:**
image

**Validate the Database:**
image

**Edit a License and add the License Type:**
image

**Delete a used license Type:**
image

**Delete a license type:**
image

**Comment by quan-tv** [comment]
Hi @ravi110336,

Like @KoukiHama-san already asked in issue #936 

https://github.com/eclipse/sw360/issues/936#issuecomment-828208080

I also got no idea what is the purpose of the field 'licenseTypeId'. Checking the source code, I also found out that it was not used anywhere. But I think it is a little risky if we remove this field (maybe it is being used in older version), so I decided to keep it.

The value of licenseTypeId will be hash code of licenseType.

Because licenseType is unique, licenseTypeId will also be unique.

https://github.com/eclipse/sw360/blob/aae02e3e811794e5cde76868802cb4e483fcd884/backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java#L486

**Comment by ravi110336** [comment]
Thanks @quan-tv. we can merge this now.

**Comment by mcjaeger** [comment]
let's follow up on this ting: https://github.com/eclipse/sw360/issues/1284

**Pull request merged**
