### PR TITLE
fix(ui): Display url, email, text  of Additional Data for Component/Release

### PR DESCRIPTION
**Pull request by tuannn2**
…nd Release

Signed-off-by: tuan99123 <tuan2.nguyennhu@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #1506 

### How To Test?
Please refer issue: #1506

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by tuannn2** [comment]
@akapti I have finished rebase . Please check it!

**Review by akapti — COMMENTED** [review]
Tested the PR, working fine without any issues.
Code looks good to me, except the duplication part.
These 2 files have identical piece of code. `includes/components/detailOverview.jspf` and `includes/releases/detailOverview.jspf`.
It would be great if the identical code can be moved to any common file.

**Comment by tuannn2** [comment]
Thank you for your reviewing, @akapti . I have fixed it according to your review. Please check it!

**Review by akapti — APPROVED** [review]
Code looks good.

**Pull request merged**
