### PR TITLE
Chore(licenseinfo): Add separate DOCX template for reports

### PR DESCRIPTION
**Pull request by dreh23**
To address different docx templates for license report generation the switch was refactored. Additionally the template was duplicated, but is still a duplicate from the old template.

### CODE REVIEW

**Comment by dreh23** [comment]
#376

**Comment by dreh23** [comment]
I am not quite sure why the ip-validation fails. See attached picture below:

eca

**Comment by mcjaeger** [comment]
maybe two things: 1) propagation time and 2) this is not a "git commit -s" ... which facilitates the signed-off-by in the commit message which is missing in your commit message

**Comment by dreh23** [comment]
Forced push with commit -s. IP-validation seems to work now.

**Comment by maierthomas** [comment]
@dreh23 please change the PR title and commit message name.
Suggestion: chore(licenseinfo): Add separate DOCX template for reports

**Comment by maierthomas** [comment]
tested successfully.

Both reports could be generated with that implementation.

**Pull request merged**
