### PR TITLE
log4j version upgrade to 2.16.0(log4j-vulnerability)

### PR DESCRIPTION
**Pull request by ag4ums**
Signed-off-by: Anupam Ghosh <anupam.ghosh@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
update the log4j version to 2.15.0 due to 
https://github.com/advisories/GHSA-jfh8-c2jp-5v3q

Issue: 

### How To Test?
test the areas that specific to logging

### CODE REVIEW

**Comment by KoukiHama** [comment]
This commit will solve https://github.com/eclipse/sw360/issues/1429

**Comment by KoukiHama** [comment]
FYI:[ANNOUNCE] Apache Log4j 2.16.0 Released
https://lists.apache.org/thread/d6v4r6nosxysyq9rvnr779336yf0woz4

**Review by JaideepPalit — COMMENTED** [review]
Code looks fine to me.
However kindly look into these following comments.

- https://github.com/eclipse/sw360/issues/1429#issuecomment-992276096
- https://github.com/eclipse/sw360/pull/1431#issuecomment-993183525
- Also kindly look into osgi dependencies
image

**Comment by ag4ums** [comment]
@JaideepPalit liferay 7.4 and above are effected with log4j vulnerability, 
(according to me)  sw360 users using liferay < 7.4 updating the log4j version should be fine ....

**Comment by ag4ums** [comment]
jar dependencies: 

| Depedency Name-version | depedency check link | comment | current status  | action require |
| ----- | -------- | ------- | ----- | ----- |
| commons-codec-1.12.jar | https://mvnrepository.com/artifact/commons-codec/commons-codec/1.12 | No log4j dependency | -NA- | no update require |
| commons-compress-1.20.jar | https://mvnrepository.com/artifact/org.apache.commons/commons-compress/1.20 | No log4j dependency | -NA- | no update require |
| commons-collections4-4.4.jar | https://mvnrepository.com/artifact/org.apache.commons/commons-collections4/4.4 | No log4j dependency | -NA- | no update require |
| commons-csv-1.4.jar | https://mvnrepository.com/artifact/org.apache.commons/commons-csv/1.4 | No log4j dependency | -NA- | no update require |
| commons-io-2.6.jar | https://mvnrepository.com/artifact/commons-io/commons-io/2.6 | No log4j dependency | -NA- | no update require |
| commons-lang-2.4.jar | https://mvnrepository.com/artifact/commons-lang/commons-lang/2.4 | No log4j dependency | -NA- | no update require |
| commons-logging-1.2.jar | https://mvnrepository.com/artifact/commons-logging/commons-logging/1.2 | has dependency | updated to version use 2.16.0 | update require |
| gson-2.8.5.jar | https://mvnrepository.com/artifact/com.google.code.gson/gson/2.8.5 | No log4j dependency | -NA- | no update require |
| guava-21.0.jar | https://mvnrepository.com/artifact/com.google.guava/guava/21.0 | No log4j dependency | -NA- | no update require |

**Comment by KoukiHama** [comment]
FYI : 2.17 release note 

https://github.com/apache/logging-log4j2/blob/6b1581901ba7a107cdc4a2208ecec03655722b44/RELEASE-NOTES.md

**Pull request merged**
