### PR TITLE
feat(licensemodel): Drop Risk and Risk category and merge it with Obligation

### PR DESCRIPTION
**Pull request by smrutis1**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
  * Which issue is this pull request belonging to and how is it solving it? (*#1004*)
  * Did you add or update any new dependencies that are required for your change? - No

Issue: 

### How To Test?
 * Need to test license import and export functionality along with adding obligation to license.
> Have you implemented any additional tests? - No

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

### CODE REVIEW

**Review by JaideepPalit — COMMENTED** [review]
Need to add Readme.md, Apart from that Code looks good to me.

**Comment by mcjaeger** [comment]
@JaideepPalit  you mean like add the scripts to the readme.md in migrations?

**Comment by JaideepPalit** [comment]
> @JaideepPalit you mean like add the scripts to the readme.md in migrations?

yes

**Comment by smrutis1** [comment]
Updated the `Readme.md`

**Comment by smrutis1** [comment]
(from discussion): 
Removed unnecessary print statements and updated the log output messages for `036_drop_old_views_and_license_field_update.py`

**Review by mcjaeger — APPROVED** [review]
testing was without errors on our clone from produtive

**Comment by mcjaeger** [comment]
@JaideepPalit please feel free to merge it, if you feel your issue is solved appropriately

**Review by JaideepPalit — APPROVED** [review]

**Pull request merged**
