### PR TITLE
fix(businessrules): NPE in clearingStateSummaryComputer

### LINKED ISSUE #713: NPE in computeReleaseClearingStateSummary
When entering Project-portlet (main Projects view)`computeReleaseClearingStateSummary` fails with NPE at line 39 in ReleaseClearingStateSummaryComputer.

https://github.com/eclipse/sw360/blob/0122f1a21a90cba4c7690159ec48e46ef3f2bd4c/libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/businessrules/ReleaseClearingStateSummaryComputer.java#L38-L42

**Stacktrace:**
```
  2019-11-06 11:16:54 ERROR ProcessFunction:47 - Internal error processing fillClearingStateSummaryIncludingSubprojects
   java.lang.NullPointerException
         at org.eclipse.sw360.datahandler.businessrules.ReleaseClearingStateSummaryComputer.computeReleaseClearingStateSummary(ReleaseClearingStateSummaryComputer.java:39)
         at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.lambda$fillClearingStateSummaryIncludingSubprojects$3(ProjectDatabaseHandler.java:666)
         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
         at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
         at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.fillClearingStateSummaryIncludingSubprojects(ProjectDatabaseHandler.java:657)
         at org.eclipse.sw360.projects.ProjectHandler.fillClearingStateSummaryIncludingSubprojects(ProjectHandler.java:253)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$fillClearingStateSummaryIncludingSubprojects.getResult(ProjectService.java:2632)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Processor$fillClearingStateSummaryIncludingSubprojects.getResult(ProjectService.java:2612)
         at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
  2019-11-06 11:16:54.024 ERROR [http-nio-8080-exec-338][ProjectPortlet:1154] Could not get summary of release clearing states for projects and their subprojects!
  org.apache.thrift.TApplicationException: Internal error processing fillClearingStateSummaryIncludingSubprojects
         at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Client.recv_fillClearingStateSummaryIncludingSubprojects(ProjectService.java:905)
         at org.eclipse.sw360.datahandler.thrift.projects.ProjectService$Client.fillClearingStateSummaryIncludingSubprojects(ProjectService.java:891)
         at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.getWithFilledClearingStateSummaryIncludingSubprojects(ProjectPortlet.java:1152)
         at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.serveGetClearingStateSummaries(ProjectPortlet.java:449)
         at org.eclipse.sw360.portal.portlets.projects.ProjectPortlet.serveResource(ProjectPortlet.java:189)
         at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:146)
         at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:88)
         at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:140)
         at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:78)
         at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
         at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
         at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
         at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:40)
         at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:569)
         at com.liferay.portlet.internal.InvokerPortletImpl.invokeResource(InvokerPortletImpl.java:695)
         at com.liferay.portlet.internal.InvokerPortletImpl.serveResource(InvokerPortletImpl.java:509)
         at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.serveResource(MonitoringInvokerPortlet.java:313)
         at com.liferay.portlet.internal.PortletContainerImpl._serveResource(PortletContainerImpl.java:1087)
         at com.liferay.portlet.internal.PortletContainerImpl.lambda$serveResource$4(PortletContainerImpl.java:270)
         at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:427)
         at com.liferay.portlet.internal.PortletContainerImpl.serveResource(PortletContainerImpl.java:263)
         at com.liferay.portlet.SecurityPortletContainerWrapper.serveResource(SecurityPortletContainerWrapper.java:212)
         at com.liferay.portlet.RestrictPortletContainerWrapper.serveResource(RestrictPortletContainerWrapper.java:157)
         at com.liferay.portal.kernel.portlet.PortletContainerUtil.serveResource(PortletContainerUtil.java:233)
         at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:394)
         at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:174)
         at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:415)
         at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:155)
         at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:213)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
         at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:639)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
         at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:360)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:181)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:106)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
         at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
         at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
         at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
         at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:398)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:99)
         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:124)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:370)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.servlet.filters.password.modified.PasswordModifiedFilter.processFilter(PasswordModifiedFilter.java:62)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.secure.BaseAuthFilter.processFilter(BaseAuthFilter.java:360)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:89)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.processFilter(AutoLoginFilter.java:266)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:266)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:147)
         at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:181)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
         at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
         at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
         at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
         at com.liferay.portal.servlet.filters.urlrewrite.UrlRewriteFilter.processFilter(UrlRewriteFilter.java:65)
         at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:49)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:215)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:175)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:196)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:99)
         at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:106)
         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
         at java.lang.Thread.run(Thread.java:748)
```
I am using current master at `2027eaa1cccb8d0f4fa50300b3aebc8cbdded014`

### PR DESCRIPTION
**Pull request by kallesoranko**
Fix NullPointerException which is thrown in main Projects view by clearingStateSummaryComputer.

closes #713 

Signed-off-by: Kalle Soranko <ksoranko@verifa.io>

### CODE REVIEW

**Comment by kallesoranko** [comment]
This PR would need to be tested, but since https://github.com/eclipse/sw360/pull/666 as a bad omen broke main view for single project, see https://github.com/eclipse/sw360/issues/719 that need to be fixed first. I am working on it.

**Comment by kallesoranko** [comment]
https://github.com/eclipse/sw360/pull/721 fixes issue #719 and with those changes I tested this PR as well successfully.

**Comment by mcjaeger** [comment]
@kallesoranko maybe very nitpicking, but would it be Ok to use spaces instead of tabs?

**Comment by kallesoranko** [comment]
> maybe very nitpicking, but would it be Ok to use spaces instead of tabs?

I guess using spaces or tabs would result same here but checked the best practices with `switch` - `case` and found out that they should be at same intentation level. Fixed now.

**Comment by kallesoranko** [comment]
Changed logic here a bit, so that method does not change `release.claringState`, but if it is not set that it is counted as `newRelease`, since it seems to be the best option. Better would be to have something like `undefined` as a `release.claringState` or on the other hand we could enforce setting `release.claringState` when releases are created. Any ideas about this?

**Pull request merged**
