### PR TITLE
adding docker support for java 11 builds

### PR DESCRIPTION
**Pull request by joecantwell**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
As things currently stand, SW360 requires a java 11 but the docker container provided still references java 8

> * Did you add or update any new dependencies that are required for your change?
I'm referencing gosu in the Dockerfile to allow the container to write compiled files to the mount.

@mcjaeger 

Compiled jar & war files can be deployed into a test environment

> Have you implemented any additional tests?
No

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by mcjaeger** [comment]
@joecantwell I am sorry for not telling earlier - would you mind to 1. register at eclipse.org, 2. put the gitub username in your profile there and 3. sign the eclipse CLA. Currently we have an issue
```
Anonymous (joe.cantwell@****.com) is not covered by the necessary legal agreements in order to proceed.
```

**Comment by joecantwell** [comment]
@mcjaeger, I created and eclipse acct and signed the agreement so I'm not sure why the validation steps is failing. I did open the PR before creating the eclipse acct and signing the agreement but the re-validation step seems to fail aswell. I may abandon this PR and retry

**Comment by mcjaeger** [comment]
@joecantwell but did you really use the same e-mail as in the commit log? `joe.cantwell@analog.com`

**Comment by joecantwell** [comment]
crapola. I didn't realize I used my analog address

**Comment by mcjaeger** [comment]
"applesauce" ? well anyway I guess an amend commit will not help and probably it is the best to have this PR closed and a new PR from a new branch opened.

**Comment by mcjaeger** [comment]
@joecantwell please consider reopening the branch, because it is a very nice feature!

**Comment by mcjaeger** [comment]
(ehhh, not reopen, but a new one with appropriate signed commits)

**Pull request closed without merging**
