### PR TITLE
fix(spdx license import): Change quotes marks in jsp for "Release overview from component details license import" 

### PR DESCRIPTION
**Pull request by KoukiHama**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue:  #915 

Popup message and get SPDX info from external server. 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by KoukiHama** [comment]
I forgot modify commit message and fix it tomorrow.

**Comment by mcjaeger** [comment]
I tend to merge it, since it fixes the issue of actually importing SPDX licenses again. But allow me to mention that I  came across this issue: 

https://github.com/eclipse/sw360/issues/927

Any opinions, merge this PR and treat the status message as separate issue?

**Comment by KoukiHama** [comment]
>Any opinions, merge this PR and treat the status message as separate issue?

I would like to find solution, I think  "status message broken" stems from grammar error of this line.

https://github.com/eclipse/sw360/blob/88466ae596df7d8bc1a5392cf60994f000d43d04/frontend/sw360-portlet/src/main/resources/content/Language.properties#L567

**Comment by KoukiHama** [comment]
https://github.com/eclipse/sw360/pull/930 included this changes. Now I close thid request.

**Comment by KoukiHama** [comment]
https://github.com/eclipse/sw360/pull/930 included this changes. Now I close thid request.

**Pull request closed without merging**
