### PR TITLE
fix(ui): fix issue #762, introduced in df5401472

### PR DESCRIPTION
**Pull request by maxhbr**
see also:
- https://github.com/eclipse/sw360/commit/df54014729a05e977095c187f65ce7f0d22f433f#commitcomment-36950304
- https://github.com/eclipse/sw360/issues/762

### CODE REVIEW

**Comment by mcjaeger** [comment]
I do not know why, but it is not loading. Components shows circling partial circle and the console shows this:

Screenshot 2020-01-26 at 22 35 31

(good news that vagrant virtual box works in general, however, checkout of your fork did not work ...)

**Comment by mcjaeger** [comment]
Adding to that: it is not the bug to have zero components - I have forged a request to add a component and created one ... Also with one entry (which is visible in home for example) the components list view is not loading.

**Comment by mcjaeger** [comment]
Hm, I think these two lines need to be in and should not have been deleted. I am very sorry, I did not test this thoroughly ...

https://github.com/eclipse/sw360/commit/df54014729a05e977095c187f65ce7f0d22f433f#r36971909

**Comment by maxhbr** [comment]
The PR is updated, please retest.

**Comment by mcjaeger** [comment]
still not working:

Screenshot 2020-01-27 at 10 14 59

**Comment by maxhbr** [comment]
i have also added the following snippet back in
```html
<script>
    var renderCallback = function () {
    };
    var dataGetter = function(field) {
    };
</script>
```

**Comment by mcjaeger** [comment]
me too (locally), but right now there seems to be test failure again, I am on it and will report if done.

**Comment by mcjaeger** [comment]
looks good, but let me test with a clean checkout

**Pull request merged**
