### PR TITLE
chore(migration) Avoid null pointer on script 048_add_component_busin…

### PR DESCRIPTION
**Pull request by dineshr93**
This pull request resolves this issue https://github.com/eclipse/sw360/issues/1821#issue-1565917274 in the migrationscript 048
Issue:

Suggest Reviewer
@KoukiHama

### CODE REVIEW

**Review by KoukiHama — APPROVED** [review]
Code and my test was OK

**Comment by dineshr93** [comment]
> @dineshr93 can you register eclipsefdn/eca 
> Codes and test in my environment is ok

I have registered and signed eclipse eca. Please let me know if I am missing something now And I should take care in subsequent commits.

**Comment by KoukiHama** [comment]
I found the reason why eca return error.
Please add sign-off when you commit. Like this.

image

In your case, it does not exsit.
image

**Comment by KoukiHama** [comment]
Thank you and sorry I verified eca. 
Now everything is fine.
I verified eca.

**Pull request merged**
