### PR TITLE
fix(ui): Vulnerabilities relevance rating (tooltip) is not shown properly

### PR DESCRIPTION
**Pull request by quan-tv**
Signed-off-by: Tran Vu Quan <quan1.tranvu@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Issue: After changing the relevance of a CVE within the project's vulnerability view, the relevance rating in the pop-up box is not displayed properly.
>
> Solution: Correct the mechanism how relevance rating (DataTable tooltip) is rendered and displayed.

Issue:  #1042 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by smrutis1** [comment]
@quan-tv , I followed the instruction mentioned above to do a local set up of cve-search, however I am getting the this [error.txt](https://github.com/eclipse/sw360/files/6738191/error.txt). Could you please let me know if I am missing anything here. Even I tried with the [CVE-Search-Docker](https://github.com/cve-search/CVE-Search-Docker), I am getting similar type of error.

**Comment by quan-tv** [comment]
@smrutis1 

Could you please let me know which step did you get this error?

**Comment by smrutis1** [comment]
> Could you please let me know which step did you get this error?

In step 6, while synchronizing the data from CVE server. 

Also I tried directly their(cve) REST endpoint, this is what I am getting. Any hint?
image
And there is no error during setup except one warning while running `./sbin/db_updater.py -v`
image

**Comment by quan-tv** [comment]
I'm checking right now, please wait for a while.

By the way, could you please access localhost:5000 with your browser?
This is the homepage of CVE Search server.

**Comment by smrutis1** [comment]
Thanks , 

I am able to access the homepage.

1. 
image



2. 
image

**Comment by nam-np** [comment]
#1121

**Comment by smrutis1** [comment]
@quan-tv , @nam-np Thanks, Apparently changing the order of execution of step 7 and 8 worked for me.
image

**Review by smrutis1 — APPROVED** [review]
Code looks fine to me and tested successfully.

**Comment by KoukiHama** [comment]
@mcjaeger 

This markdown file is very useful.
https://github.com/eclipse/sw360/files/6698844/SW360-CVE-mannual-20210621.md

Wouldn't it be nice to post this markdown file on the Wiki?

**Comment by mcjaeger** [comment]
> @mcjaeger
> 
> This markdown file in @quan-tv 's first post here is very useful.
> 
> https://github.com/eclipse/sw360/files/6698844/SW360-CVE-mannual-20210621.md
> 
> Is it be to post this markdown file on the sw360 [Wiki](https://github.com/eclipse/sw360/wiki)?

absolutely, maybe just a new page here: https://github.com/eclipse/sw360/wiki#general-deployment-guides

**Comment by quan-tv** [comment]
> @quan-tv , @nam-np Thanks, Apparently changing the order of execution of step 7 and 8 worked for me.
I updated the execution: swap position of step 7 and step 8.

**Comment by KoukiHama** [comment]
> absolutely, maybe just a new page here: https://github.com/eclipse/sw360/wiki#general-deployment-guides

I made a page : https://github.com/eclipse/sw360/wiki/Deploy-CVE-search
And add link here :  https://github.com/eclipse/sw360/wiki#general-deployment-guides

**Comment by smrutis1** [comment]
closes: #1151

**Pull request merged**
