### PR TITLE
feat(ProjectUI): Added 2 new fields in Project Obligation

### LINKED ISSUE #992: ProjectUI: Add 2 new fields in Obligation table under project details/edit page.
* Two new fields (obligation) `type` and `id` should be added in Project Obligations from CLI file.
* Fix the text overflow for `Obligation` column in table.

### PR DESCRIPTION
**Pull request by akapti**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
* Added 2 new fields `type` and `id` in `ObligationsAtProject` table (as shown in below screenshot).
* These field values are fetched from parsed `CLI` files from `Linked Release`.
* Modified `Project Clearing Report` to include `type`.
* Fixed the text overflow for `obligation` column in table. (for both edit/detail page).

image

Note: There should be only one `Approved CLI file` in each Release for obligations to load.

closes #992 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Abdul Kapti <abdul.mannankapti@siemens.com>

### CODE REVIEW

**Comment by mcjaeger** [comment]
Proposed obligation types:
* Permission
* Restriction
* Obligation
* Risk
* Exception

**Comment by mcjaeger** [comment]
I just skimmed over the code: I would have a question: there is no migration script for removing action, because it was not used at all?

**Comment by akapti** [comment]
> I just skimmed over the code: I would have a question: there is no migration script for removing action, because it was not used at all?

It was never used, so we don't need migration script.. maybe the commented code (for action) should be removed in future, to avoid confusion.

**Review by JaideepPalit — APPROVED** [review]
Code looks fine to me . Needs to be tested.

**Comment by mcjaeger** [comment]
tested: seems to work perfectly.

**Pull request merged**
