### PR TITLE
fix(rest): Create/Update Release with name same as component name

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Create/Update Release with name same as component name
> * Which issue is this pull request belonging to and how is it solving it? (*#1078*)
> * Did you add or update any new dependencies that are required for your change?

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Review by smrutis1 — CHANGES_REQUESTED** [review]
Two remarks:
* Error message should contain also the version string along with the name.
* As there is no significant of passing `name` while creating release from REST anymore. Could it be removed from the REST docs as well.

**Comment by JaideepPalit** [comment]
Thanks for review. 

> * Error message should contain also the version string along with the name.
      - fixed

> * As there is no significant of passing `name` while creating release from REST anymore. Could it be removed from the REST docs as well.
      - removed

**Comment by smrutis1** [comment]
One minor comment:

In documentation, created on filed is appearing where as it's actually not coming in the response. Could it be removed?

image

image

**Comment by JaideepPalit** [comment]
> In documentation, created on filed is appearing where as it's actually not coming in the response. Could it be removed?  
    - removed

**Review by smrutis1 — APPROVED** [review]
Code looks fine to me. Tested it successfully as well.

**Pull request merged**
