### PR TITLE
feat(rest): Added missing fields to REST API json

### PR DESCRIPTION
**Pull request by smrutis1**
* Added project responsible, security responsible and programming language, fields to the REST API json of project and release records respectively.

closes: #499, #498 , #489 

Signed-off-by: Smruti Sahoo <smruti.sahoo@siemens.com>

### CODE REVIEW

**Comment by maxhbr** [comment]
one also needs to add tests and documentation for `projectResponsible` and `languages` right? (At least as far as I understand the tests)

**Comment by smrutis1** [comment]
Thanks for pointing it out. I have added respective tests and documentation. Kindly review.

**Comment by mcjaeger** [comment]
@smrutis1 please consider rebasing

**Comment by smrutis1** [comment]
@mcjaeger  Rebased after resolving the merge conflict.

**Comment by nutanv1contr** [comment]
I have tested the new fields added to REST API.Functionality is working as expected.
**Below are the scenarios tested:**
1.Get request for specific projects and view the fields "securityResponsibles", "projectResponsible" are populating.
2.Get request for specific releases and view the field "languages" is populating. 
3.Make a create project request with new fields "securityResponsibles", "projectResponsible" , and check if the fields is getting saved successfully.
3.Make a create release request with new field "languages" and check if the field is getting saved successfully.

**Comment by nutanv1contr** [comment]
Document generation is also successful for the new fields.

**Pull request merged**
