### PR TITLE
fix(merge): fix update conflict on component merge

### LINKED ISSUE #208: Merge Components may fail in last step because of database update issue
<a href="https://github.com/mcjaeger"></img></a> **Issue by [mcjaeger](https://github.com/mcjaeger)**
_Monday Jan 22, 2018 at 09:59 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/723_

----

(Alex and me) When merging a component, the last write to the target may fail at last write of plain fields at:

https://github.com/sw360/sw360portal/blob/e90785fb89e584eb3094fbc002787ddf7bdc9570/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java#L476

because of an update conflict when the releases are merged, but the components dataset is not retrieved again.

In the stack trace below merging releases is at rev 20 resulting in rev 21, then plain fields write following does not see rev 20 as latest, but Java code call is at that level.

```
2018-01-22 12:01:45 ERROR DatabaseConnector:180 - Document cannot be updated Component(id:1cfc47ff...)
 org.ektorp.UpdateConflictException: document update conflict: id: 1cfc47ff3694425ac5e98f23a2355d90 rev: 20-0fb05174942c3e1a559b1dd3eba9a27d
        at org.ektorp.impl.StdCouchDbConnector$9.error(StdCouchDbConnector.java:378)
        at org.ektorp.impl.StdCouchDbConnector$9.error(StdCouchDbConnector.java:364)
        at org.ektorp.http.RestTemplate.handleResponse(RestTemplate.java:126)
        at org.ektorp.http.RestTemplate.put(RestTemplate.java:47)
        at org.ektorp.impl.StdCouchDbConnector.update(StdCouchDbConnector.java:363)
        at org.eclipse.sw360.datahandler.couchdb.DatabaseConnector.update(DatabaseConnector.java:177)
        at org.ektorp.support.CouchDbRepositorySupport.update(CouchDbRepositorySupport.java:181)
        at org.eclipse.sw360.datahandler.db.ComponentDatabaseHandler.updateComponentInternal(ComponentDatabaseHandler.java:417)
        at org.eclipse.sw360.datahandler.db.ComponentDatabaseHandler.updateComponentCompletely(ComponentDatabaseHandler.java:593)
```

### PR DESCRIPTION
**Pull request by lepokle**
This commit fixes an update conflict during component merge if the
components had releases.

This commit also changes the merge logic a little bit and introduces
some error handling:

* merge is done in a try-catch block and a merge error is shown on the client
* merge workflow has been cleaned up. Component are only touched ones, releases afterwards.
* releases are all merged. This cannot be changed by user.
* release name is always overwritten by target component name
* do not catch exception inside DatabaseConnector

Fixes #208 

Signed-off-by: Leo von Klenze <leo.vonklenze@scansation.de>

### CODE REVIEW

**Comment by nutanv1contr** [comment]
Tested the PR. Functionality is working correctly. 
1. Able to merge component successfully with target component.
2. Merged component fields as well as releases are reflecting on the target component.

**Comment by lepokle** [comment]
Since I've made changes on the merge wizard in PR #663 and PR #680 as well, I've consolidated these changes and append them to all PRs. This way the general improvements are available in every PR which makes it easier to review and to develop the next PR for merging releases.

The last force-push contains these general improvements (error handling, style).

**Comment by nutanv1contr** [comment]
Tested the PR again. Functionality is working as expected.

**Comment by nutanv1contr** [comment]
Code looks good to me except one minor indentation.

**Pull request merged**
