### PR TITLE
feat(external-tool-request): added general datastructure for external tool requests

### PR DESCRIPTION
**Pull request by imaykay**
* refactored fossology requests structure to a generic one
* refactored also a lot of tests
* gui remains unchanged at the moment, but there might be a special view for all external tool requests of a release
* added migration script for release objects (not checking moderation requests)

closes eclipse/sw360#93

Signed-off-by: Andreas Klett <andreas.klett@scansation.de>

### CODE REVIEW

**Comment by imaykay** [comment]
Please be aware that this PR is not yet tested completely by myself. But I thought it might be a good idea to get first feedback from review and tests on existing instances until I am back from vacation.

**Comment by imaykay** [comment]
Because of rebasing to the current master, the build fails in cvesearch.

**Comment by imaykay** [comment]
@mcjaeger what exactly are the issues in the UI? Do you have screenshots or a description? Or are we planning to fix them with #607 where most gui parts will be rewritten completely?

**Comment by imaykay** [comment]
Rebased on current master with Liferay 7.

**Comment by mcjaeger** [comment]
will retest it after the rebase

**Comment by mcjaeger** [comment]
retest: updated also our stage data base and migrated the items for us successfully.

**Pull request merged**
