### PR TITLE
feat(license-disclosure): External Ids incorporated in the license disclosure

### PR DESCRIPTION
**Pull request by smrutis1**
* Incorporated the project external Ids chosen by the user in the license disclosure document. 
* Changes are done in both UI as well as rest side.

Signed-off-by: Smruti Sahoo <smruti.sahoo@siemens.com>

### CODE REVIEW

**Comment by nutanv1contr** [comment]
Hi @smrutis1 ,
Below are the suggested changes:
*  There is a extra text coming in disclosure document "ExtIdInDisclosure".
*  Could you please improve the alignment of external id table in the disclosure document.
image
*  To select the externalIds added in disclosure document, is it possible to improve the UI by adding alignment to the external ids displayed.

**Comment by mcjaeger** [comment]
maybe it could be like the following:

```
External references for this product
```

with table header:

```
| Reference Name | Reference Value |
```

**Comment by nutanv1contr** [comment]
Tested the PR.

**Issues found:**
1. From rest end point "externalIds" property is mandatory. Without that response status gives 500 error response.

**Below are the scenarios tested successfully:**
1. On click of "Download" button from "Generate License Info" screen, a popup will appear which list the external ids to be selected and output format. Click "Download" button after selecting the external ids and output format, it will generate the document successfully.Tested the same for xtml,docs and text format.
2. External ids are displayed as check box which enables to select multiple external id and document format is coming as radio button.
3.  External id selection is saved until user exits from "Generate License Info" tab.

Browser: Chrome (V76.0.3809.132), Firefox (V60.8.0)

**Comment by smrutis1** [comment]
@nutanv1contr , Thanks for pointing it out. Corrected the issue w.r.t REST endpoint.

**Comment by nutanv1contr** [comment]
@smrutis1 , Tested the feature again. externalIds input property is not mandatory anymore. feature is working as expected.

**Pull request merged**
