### PR TITLE
fix(CouchDbView): Improve couchdb view performance

### PR DESCRIPTION
**Pull request by akapti**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

1. Changed the `couchdb` view not to emit the whole documents.

Issue: #1604 

### How To Test?
Make sure all the SW360 documents are loading (creation / updating / deletion) fine in UI.
Specifically:

1. Attachments,
2. Attachment Usages,
3. Change Logs,
4. Configs,
5. Obligations (Org, Project, Component and License),
6. Vulnerabilities (Rating, Relation),
7. License,
8. License Types,
9. Clearing Request,
10. OAuth tokens.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR
Signed-off-by: Abdul Kapti <abdul.kapti@siemens-healthineers.com>

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Testing was unsuccessful as CouchDbView still emitting the whole document.

**Comment by akapti** [comment]
> Testing was unsuccessful as CouchDbView still emitting the whole document.

I re-tested in my local sandbox and it was working as expected.
@smrutis1 @nikkuma7 Can you give it a try for testing?

**Comment by akapti** [comment]
Deployed and tested this change in SHS server.
The disk usage is reduced by huge amount. as shown ins screenshots below:
The `ChangeLogs` view size has been reduced: 
Actual data size reduced from: `2304 MB` to `125 MB`.
Data size on disk reduced from: from `8148 MB` to `73 MB`

**Before Deployment:**
SW360_Stage_ChangeLogd_View_2022-10-05 19_23_12


**After Deployment:**
SW360_Prod_ChangeLogs_View_2022-10-05 19_25_02

**Comment by akapti** [comment]
@ag4ums @smrutis1 
This PR is deployed in SHS SW360 Stage from past 2 days and everything working fine without any issues.
Marking the PR as ready.
Let me know if anyone have any concerns regarding this PR.

**Review by ag4ums — APPROVED** [review]
Changes looks good

**Pull request merged**
