### PR TITLE
fix(ui): Changes in External urls in Project are not registered in Moderation Request. Closed Moderation Request doesnot show Proposed changes

### LINKED ISSUE #1343: Changes in External urls in Project are not registered in Moderation Request. Closed Moderation Request doesnot show Proposed changes
### Description

Changes in External urls in Project are not registered in Moderation Request. Closed Moderation Request doesnot show Proposed changes

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: closes #1343 

> Check Open/Closed Moderation Request for Project, Component, Release, License, User. should contain proposed changes. Also need to test Accept/Reject.

> Have you implemented any additional tests?

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Review by smrutis1 — APPROVED** [review]
Code looks good to me.

**Comment by smrutis1** [comment]
For closed moderation requests, the "Proposed Changes" is appearing, however. it is always empty

image

**Comment by JaideepPalit** [comment]
> But for closed moderation requests, the "Proposed Changes" is appearing, however. it is always empty
>    - Fixed for
>        -  add/delete/update Basic field like `version>
>        -  add/delete/update Set/Map like External Id, categories in release
>        -  add/delete/update attachments
>        -  add/delete/update linked release/projects

**Comment by smrutis1** [comment]
Tested it. Seems to work

**Pull request merged**
