### PR TITLE
fix(ModerationRequest): Fixed Moderation Request not opening when associated attachment deleted

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Fixed Moderation Request not opening when associated attachment deleted
> * Which issue is this pull request belonging to and how is it solving it? (*#1026*)
> * Did you add or update any new dependencies that are required for your change?

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by JaideepPalit** [comment]
Tested similar scenario with external-id , linked release and project.
Moderation request seems to open and work when clicked on `accept` button

**Comment by smrutis1** [comment]
Code looks Ok to me.

Is it possible to make the message more clear by changing may be the color to RED or displaying it in the table row. (Optional)

ErroMsg

**Comment by JaideepPalit** [comment]
Changes made added red color to highlight missing attachment.

image

**Review by smrutis1 — APPROVED** [review]
Code looks good to me. Tested successfully.

**Pull request merged**
