### PR TITLE
feat(ui): Banner to Broadcast Messages

### PR DESCRIPTION
**Pull request by rudra-superrr**
Signed-off-by: rchopra [rudra.chopra@siemens.com](mailto:rudra.chopra@siemens.com)

Issue: Add banner to broadcast messages (https://github.com/eclipse/sw360/issues/1595)

Description : This functionality can be edited by Admins only.

How To Test?
1. Click on 9 dots on the top right section of the page
2. Go to control panel -> click custom fields under configuration
3. Select User under Resource section
4. There you will see BannerMessage custom field.
5. Click on three dots to edit this field. Here you can enter message that you want to be displayed.
6. Right click on three dots and give view permission to all sw360 users/roles and change other permissions too. (Refer the ss for this step)

### Screenshots

controlPanel
Click custom field under control panel section

User
Select User under resource section

bannerMessage
Banner Message custom field should look like this

Permissions
Give view permission to all sw360users/roles and make changes in other permissions too

welcomePage
Banner message on top of the page

### CODE REVIEW

**Comment by nikkuma7** [comment]
Test successful.

image

**Review by akapti — CHANGES_REQUESTED** [review]
Please fix the indentation issue in most of the JSP files (though I have commented only in one file).
Also, it would have been a good approach if we can modify a centralized file and include that centralized file in all JSP rather than doing exact same changes in all the files.

**Comment by rudra-superrr** [comment]
Hi @akapti , fixed the indentation issue.

**Review by akapti — APPROVED** [review]
Approving the PR.
But again it would have been a good approach if we can modify a centralized file and include that centralized file in all JSP rather than doing exact same changes in all the files.

maybe we can create a new issue and try to find improved approach then the current one.

**Comment by nikkuma7** [comment]
Getting below error :
image

**Comment by ag4ums** [comment]
reverting the PR....  due to the above issue...

**Pull request merged**
