### PR TITLE
chores(liferay): updated liferay kernel and theme

### PR DESCRIPTION
**Pull request by akapti**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

- Updated the Liferay kernel version to `43.0.1` to make it compatible with Liferay 7.4.3-GA18.
- Updated the Liferay theme dependency.
- Minor UI issues like user menu dropdown are fixed.

issue screenshot: 
image

- Fixed the `src-cvesearch` test case failure in for Asian time zone.

Issue: #1637 

### How To Test?

- Build Liferay without skipping testcase,
- Deploy sw360, and test all the portlet UI is loading properly, and able to edit all the documents.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: akapti <abdul.kapti@siemens-healthineers.com>

### CODE REVIEW

**Comment by akapti** [comment]
build is successful in my local environment. even though there are error at exact same point where the CI/CD build is failing.
```
[INFO] --- com.liferay.css.builder:3.0.2:build (default-build-css) @ liferay-theme ---
Using native Sass compiler
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
Parsed /css/clay.scss in 2807ms
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[ERROR] Illegal character: <
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
[WARNING] Media expression uses unknown feature 'prefers-reduced-motion'
Parsed /css/main.scss in 980ms
```

Final output:
```
[INFO] frontend ........................................... SUCCESS [  0.073 s]
[INFO] sw360-portlet ...................................... SUCCESS [ 21.535 s]
[INFO] liferay-theme ...................................... SUCCESS [  7.604 s]
[INFO] rest ............................................... SUCCESS [  0.113 s]
[INFO] rest-common ........................................ SUCCESS [  0.528 s]
[INFO] authorization-server ............................... SUCCESS [ 29.970 s]
[INFO] resource-server .................................... SUCCESS [01:44 min]
[INFO] clients ............................................ SUCCESS [  0.078 s]
[INFO] http-support ....................................... SUCCESS [  6.018 s]
[INFO] client ............................................. SUCCESS [ 14.518 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:49 min
[INFO] Finished at: 2022-09-14T13:02:06+05:30
[INFO] ------------------------------------------------------------------------
```

**Comment by heliocastro** [comment]
Despite the modules of **oauth2** and **license types** been readded, still functionality is not working.
Panels aren't matching new liferay model, example:

Regular module, is possible disable liferay details ( look above ):
image

Oauth module can't:
image

And ouath2 is not authenticating anymore

**Comment by akapti** [comment]
> build is successful in my local environment. even though there are error at exact same point where the CI/CD build is failing.

Build is successful here after updating the `Liferay CSS builder` version to `3.1.0`

**Comment by mcjaeger** [comment]
(from meeting) oauth issue should be fixed by https://github.com/eclipse/sw360/pull/1632 - retest after rebase.

**Comment by heliocastro** [comment]
@mcjaeger I would say from my side that we should merge this PR right now, and solve the remaining issues, which is mostly resource server and oauth from the **rest**
Most of the operations are ok, and then we can focus on this specific parts.
@ag4ums @KoukiHama  ?

**Comment by mcjaeger** [comment]
@heliocastro maybe it is a good idea - I was not able to start it:
```
26-Sep-2022 08:19:54.626 SEVERE [main] org.apache.catalina.startup.ContextConfig.processContextConfig Parse error in context.xml for []
sw360               | 	org.xml.sax.SAXParseException; systemId: file:/app/sw360/tomcat-9.0.56/conf/Catalina/localhost/ROOT.xml; lineNumber: 2; columnNumber: 79; Error at line [2] column [79]: [com.liferay.support.tomcat.util.scan.NOPJarScanner]
```

**Pull request merged**
