### PR TITLE
chore(cleanup): drop unused and outdated code reated to the codescoop integration

### PR DESCRIPTION
**Pull request by maxhbr**
This PR compiles and tests pass on my machine.

This should revert most of:
- https://github.com/eclipse/sw360/commit/ed79f9a
- https://github.com/eclipse/sw360/commit/28b0c64
- https://github.com/eclipse/sw360/commit/4722f04

### CODE REVIEW

**Comment by maxhbr** [comment]
ping @mcjaeger

**Comment by mcjaeger** [comment]
Travis CI build failing at exit ...

**Comment by maxhbr** [comment]
aren't all travis runs failing?

**Comment by mcjaeger** [comment]
@maxhbr no reason to get exited about it, I was just too brief with my remark. I meant to say:

```
I have seen the travis being red and thus I have checked the travis log and saw the same old error again that it fails at exit after all targets were running through with "SUCCESS". So I have checked the travis and no one else need to click through the build log again to check why the travis ci check is red.
```

**Comment by maxhbr** [comment]
Now it is green.

**Pull request merged**
