### PR TITLE
feat(rest): new endpoint `/projects/myprojects`

### PR DESCRIPTION
**Pull request by GMishx**
New `/projects/myprojects` to list projects for home page's "My Projects" table.

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Please provide a summary of your changes here.
* Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
  * Part of #1826
* Did you add or update any new dependencies that are required for your change?
  * No

### How To Test?
**How should these changes be tested by the reviewer?**
> Test the rest endpoint `/projects/myprojects` with various parameter combinations and compare the response with the UI.

**Have you implemented any additional tests?**
> No

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Was not able to get the desired result as there is bug in My Projects dropdown selection.
Refer issue : #1836

**Comment by rudra-superrr** [comment]
Testing was successful.

**Comment by smrutis1** [comment]
Please consider adding documentation

**Comment by GMishx** [comment]
> Please consider adding documentation

Added the documentation @smrutis1 . Please have a look.

**Review by smrutis1 — APPROVED** [review]
Code looks good

**Pull request merged**
