### PR TITLE
chore(couchdb): Support CouchDb Lucene 2.1.0 with CouchDb 2.1.2 and backward compatibility

### PR DESCRIPTION
**Pull request by JaideepPalit**
> Support CouchDb Lucene 2.1.0 with CouchDb 2.1.2 and backward compatibility
> * Which issue is this pull request belonging to and how is it solving it? (*#415*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: 

> **Backward Compatibility**
> Install `CouchDb lucene 1.0.2 - Couch DB 1.6.0` follow [wiki](https://github.com/eclipse/sw360/wiki/Deploy-Natively#deploy-couchdb), Add `_fti` hook to `/etc/couchdb/local.ini` of couchdb . 
> ```
> [httpd_global_handlers]
> _fti = {couch_httpd_proxy, handle_proxy_req, <<"http://[TOMCAT_INSTANCE]/couchdb-lucene">>}
> ```
> Search Functionality should be working fine

> **Steps to deploy couchdb-lucene**
> 1.  Download and rename src from github
>     -  wget https://github.com/rnewson/couchdb-lucene/archive/v2.1.0.tar.gz -O couchdb-lucene.tar.gz
> 2.  Extract src
>     -  tar -xzf couchdb-lucene.tar.gz
> 3.  cd couchdb-lucene-2.1.0
> 4.  Edit and make changes to `couchdb-lucene.ini` not required for local setup
>     -  vim ./src/main/resources/couchdb-lucene.ini
> 5.  Download patch
>     -  wget https://raw.githubusercontent.com/sw360/sw360vagrant/master/shared/couchdb-lucene.patch
> 6.  Apply patch
>     -  patch -p1 < couchdb-lucene.patch
> 7.  Build sources
>     -  mvn clean install war:war
> 8.  Copy and rename war file to webapps
>     -  cp ./target/*.war /<liferay>/<tomcat>/webapps/couchdb-lucene.war

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

### CODE REVIEW

**Comment by mcjaeger** [comment]
I am not sure, if the provided information is sufficient to test this branch successfully:

* install this branch
* install couchdb 2.1.2 on xenial (which is an attempt on its own)
* install ocuhdb lucene .21 built from source (download release source from github and then remove old lucene and install new lucene
* create `couchdb.properties` in /etc/sw360 with the above mentioned data

-> search does not work, see screenshot. I suspect that some configuration information is missing.

**Comment by mcjaeger** [comment]
screenshot:

Screenshot 2020-08-07 at 23 42 16

**Comment by mcjaeger** [comment]
BTW. if someone else attmepts to try it. some notes about the couchdb installation. Very disappointing, if you go for the official page:

Screenshot 2020-08-07 at 23 47 39

it points you to the page where you can install couchdb 3.1 (on xenial). There is such way to install any version of couchdb 2.x just from packages anymore. I downloaded the deb file from:
```
https://apache.bintray.com/couchdb-deb/pool/C/CouchDB/couchdb_2.1.2~xenial_amd64.deb
```
which does not install, because you need the couch db version (not the ubuntu package, thank you guys for making a special package for an official package) of the spidermonkey java script engine from here:
```
https://apache.bintray.com/couchdb-deb/pool/s/spidermonkey/
```
(leaving the issue with the local setting aside). THEN, couchup is necessary, which fails on our sw360db (fun ...)maybe that is a source for malfunction. IN the old installation notes there is the warning that the config file for couch 1.X needs to be adjusted or updated because it is not compatible with couch 2.X I am not sure if that is the reason because there is zero info on the web which can found what needs to be changed actually.

**Comment by mcjaeger** [comment]
after a clean vagrant setup (with manual installation of  couchdb lucene and couchdb 2.1.2:
```
2020-08-07 23:21:13.738 ERROR [http-nio-8080-exec-24][IncludeTag:128] Current URL /couchdb-lucene/local/sw360users/_design/lucene/all?include_docs=true&limit=150&q=%28+type%3Auser+%29+AND+%28%22test*%22+test*%29 generates exception: null
java.nio.BufferOverflowException
	at java.nio.Buffer.nextPutIndex(Buffer.java:524)
	at java.nio.HeapCharBuffer.put(HeapCharBuffer.java:173)
	at com.liferay.portal.kernel.io.OutputStreamWriter.write(OutputStreamWriter.java:119)
	at com.liferay.portal.kernel.io.unsync.UnsyncPrintWriter.write(UnsyncPrintWriter.java:350)
	at freemarker.ext.jsp.JspWriterAdapter.write(JspWriterAdapter.java:169)
	at com.liferay.portal.kernel.io.unsync.UnsyncPrintWriter.write(UnsyncPrintWriter.java:350)
	at org.apache.jasper.runtime.JspWriterImpl.write(JspWriterImpl.java:199)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:201)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
	at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:406)
	at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:382)
	at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:217)
	at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:88)
	at freemarker.ext.jsp.TagTransformModel$TagWriter.endEvaluation(TagTransformModel.java:400)
	at freemarker.ext.jsp.TagTransformModel$TagWriter.afterBody(TagTransformModel.java:388)
	at freemarker.core.Environment.visitAndTransform(Environment.java:427)
2020-08-07 23:21:13.739 ERROR [http-nio-8080-exec-24][PasswordModifiedFilter:62] java.lang.IllegalStateException: Cannot forward after response has been committed
java.lang.IllegalStateException: Cannot forward after response has been committed
```

**Comment by JaideepPalit** [comment]
Added `Steps to deploy couchdb-lucene` in description

**Comment by mcjaeger** [comment]
actually, installing couchdblucene is quite an adventure, thanks @JaideepPalit for the steps, I also missed to rename the servlet war file at first attempt :-(

**Pull request merged**
