### PR TITLE
fix(ui): Fixed lar file to add missing widgets(Oauth Client & License Types)

### PR DESCRIPTION
**Pull request by smrutis1**
Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

Added missing widgets(Oauth Client and License Types) in Admin section.

> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: 

### How To Test?

> How should these changes be tested by the reviewer?

In a fresh liferay install, upload the lar file and check if the Oauth client and License Types are visible and there is no error.

> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by KoukiHama** [comment]
@smrutis1  if no one review it, I will do it.

**Comment by ag4ums** [comment]
Hi @KoukiHama, i have checked it and its working fine, you can also give a try.

**Review by ag4ums — APPROVED** [review]
working as expected

**Comment by KoukiHama** [comment]
working as expected too

**Review by KoukiHama — APPROVED** [review]

**Comment by heliocastro** [comment]
Works for me as well

**Review by heliocastro — APPROVED** [review]
Just a remark.
Can you add a note explaining what was missing and how was fixed, to prevent that happens again in the future ?

**Comment by smrutis1** [comment]
Somehow while creating lar file those two widgets were missing. The same has been added by following steps:

1. Create a child page under Private Pages -> Admin -> Add Page
image
2. Click on Blank page.
image
3. Add the page name for e.g. below.
image
4. Click on Admin -> Oauth Client, then click the pencil icon in the top right corner to edit. Then search for the widget and do a drag and drop., then publish.
image
6. Then export the lar file.

**Comment by mcjaeger** [comment]
review-by:ci-test
tested-by:heliocastro@gmail.com

**Pull request merged**
